### ISSUE TITLE
Url Rewriting createHistoryEnhancer

### ISSUE THREAD

**Issue by LucaColonnello** [ReactTraining/history#292]
Hi,
I would be happy to contribute to this project.

My need now is to have the possibility to parse the location as `useBasename` do, but translating the url received into another using a configuration (like htacess rewrite url).

This would make possible to have SEO urls as we wants them without having problem with the structure of our component.

An example **(these aren't 301, but low level url rewriting)**:

```
SEO Url                               ->  App url

/news.html                            -> /news
/1566/my-article-on-history.html      -> /news/1566

```

Some ideas about how to have this as a createHistory Enhancer?
I'm thinking about something like this:

```js
import { createHistory, useUrlRewrite } from 'history'

// declare rewrite rules
const history = useUrlRewrite(createHistory)({
  rewriteRules: [
    {
      from: '/news.html',
      to: '/news'
    },
    {
      from: '/(:newsId)/(:newsTitle).html',
      to: '/news/(:newsId)'
    }
  ],

  // bestMatch or firstMatch
  // bestMatch could recognize if an url have more than one match
  // and choose for you what is the most relevant
  // based on static parts of the urls
  matchType: 'bestMatch'
})

// At the /1566/my-article-on-history.html URL:
history.listen(location => {
  console.log(location.pathname)
  // > /news/1566
  
  console.log(location.originalUrl)
  // > /1566/my-article-on-history.html
  
  console.log(location.originalParams)
  // > Object { newsId: 1566, newsTitle: 'my-article-on-history' }
})

// setter and getter
history.getRewriteRules()
// give the rewriteRules array

history.setRewriteRules([...])
// set the rewriteRules array, useful to sync with changes if the rules comes
// from a db or other storage, 

console.log(history.parseLocation('/1566/my-article-on-history.html').pathname)
// > /news/1566
// get the new location, useful for server side rendering (eg. react router match)
// or to use the algorithm with the config from other parts of the application
```

I want to start working on this, but I wanna asking for some ideas on what could be missing and also if this could make sense.

IMHO this is an essential enhancer.

**Comment by taion** [comment]
This has been open for a while. While I can see cases where this is useful, I think this is not essential functionality for interacting with browser history the same way that the existing functionality is.

I think it would make a lot of sense to create and release a package with this functionality, though.
