### ISSUE TITLE
exports.Actions is undefined?

### ISSUE THREAD

**Issue by Zae** [ReactTraining/history#305]
Hi there,

I tried using your constants from Actions (which seem to be exported), but it seems that it is undefined.

Is there another way to use the same consts?

**Comment by jmurzy** [comment]
How do you `import` them? This should work:

```js
import { Actions } from 'history';
const { PUSH, REPLACE, POP } = Actions;
```

**Comment by Zae** [comment]
hi @jmurzy,

That's exactly what I tried. I'm getting this error.

`Uncaught TypeError: Cannot read property 'PUSH' of undefined`

**Comment by taion** [comment]
This was fixed on v3 in https://github.com/ReactTraining/history/commit/b3db5e14b2b707993627833af3089ec09007376f.
