### ISSUE TITLE
Location descriptor object validation

### ISSUE THREAD

**Issue by bugron** [ReactTraining/history#310]
Currently if I write something like this:
```js
this.context.router.push({
  path: '/results',
  state: {
    playersInfo: this.state.playersInfo
  }
})
```
React app just redirects to the root (as defined [here](https://github.com/ReactJSTraining/history/blob/master/modules/LocationUtils.js#L11), note `path` is wrong in the example above, it should be `pathname`). I just start learning all this and it feels very strange that history doesn't throw any error or warning in this situation. So if I don't see an error I have to go through all my code to luckily find out that `path` actually needs to be `pathname`.
Is it possible to check that the object is a valid location descriptor otherwise throw an error?

**Comment by mjackson** [comment]
Sure, I think this is a great idea, @bugron. If you'd like to put up a PR we can discuss further. :)

**Comment by taion** [comment]
I wrote up a quick warning on https://github.com/taion/history/commit/aecc35a4e92c76fc550b7e03ca1254e7216911d2 earlier, but it would be a merge conflict against some other PRs I have up, so I'm holding off on submitting it.

**Comment by taion** [comment]
May as well put it up https://github.com/ReactTraining/history/pull/332.

I think this warning will catch a lot of typos, just because "path" is a concept, but not one that we support in location descriptors right now.
