### ISSUE TITLE
Publish flow types

### ISSUE THREAD

**Issue by c089** [ReactTraining/history#320]
The documentation has [handy type signatures](https://github.com/ReactJSTraining/history/blob/master/docs/Glossary.md), but they would be even more useful if they came as their own file so users can actually type-check their code against the.

Related note: I'm currently copy/pasting them into my own type definitions. Doing that, I found that restricting the type of `query` to `{[key:string]: string}` helps greatly to detect type errors. It is harder to read though if you're not familiar with flow, so I guess for the glossary the less strict version makes sense.

**Comment by taion** [comment]
That's not the correct signature on `query` – it depends on your choice of query serialization, which is configurable.

**Comment by c089** [comment]
Oh thanks, I didn't know about [this feature](https://github.com/ReactJSTraining/history/blob/master/docs/QuerySupport.md).

**Comment by mjackson** [comment]
@c089 That sounds great. I don't actually use Flow, so I'm not a good candidate for taking on this work. But if you'd like to put up a PR I'd be happy to discuss further.
