### ISSUE TITLE
3.0.0 breaks all JavaScript in IE8 when loaded (and not even used)

### ISSUE THREAD

**Issue by ondrejmirtes** [ReactTraining/history#321]
It worked previously.

**Comment by taion** [comment]
Do you have a repro? Are you using es5-shim/sham?

**Comment by mjackson** [comment]
I'm sorry, @ondrejmirtes, but there's not enough information here for us to do anything about it. IE8 is a really old browser. Please be sure you're using es5-shim/sham. If you can provide us with more details, we can re-open.
