### ISSUE TITLE
Use withFoo(history) enhancers

### ISSUE THREAD

**Issue by taion** [ReactTraining/history#322]
@mjackson 

This came up earlier, wanted to run it by you before I code it up – I think we should switch to e.g. `withBasename(history, basename)` instead of `useBasename(createHistory)({ basename })`.

This will make it easier to enhance e.g. the default `browserHistory` coming out of React Router, and is just otherwise a simpler API.

**Comment by mjackson** [comment]
We need to be careful to not let the RR use cases dictate too closely the work we do here. Right now it feels like this change is highly motivated by the desire to modify the pre-fab `history` objects RR exports, which I'd like to get rid of.

**Comment by taion** [comment]
That is the motivation here, but I do think this is a cleaner/easier API. Compare:

```js
withQueries(history, { parse, stringify })
useQueries(createHistory)({ parseQueryString, stringifyQuery })
```

The former reads better to me, and is more graceful in the case of user error like applying `useBasename` twice.

**Comment by mjackson** [comment]
Let's follow up in #328
