### ISSUE TITLE
Location state is inconsistent after page reloads

### ISSUE THREAD

**Issue by ddeath** [ReactTraining/history#331]
Not sure if this is bug or feature but when I am using history with react-router as browserHistory this strange thing happens:

1. Navigate to location:

        browserHistory.push({
                pathname: '/users',
                state: { fromMenu: true },
        })

2. the location on the /users has **state: { fromMenu: true }**  - this is expected so far
3. refresh the page - location has **state: { fromMenu: true }** - this is strange, i would expect it to be **state: null** 
4. refresh the page again - location has **state: null**

So what is expected behavior?
I would like it to be that state is set to null after refresh of page :smile: 

**History version:** 2.1.2
**Browser version:** Google Chrome  53.0.2774.3 dev (64-bit)
Thanks

**Comment by taion** [comment]
2 -> 3 is intended, state is meant to persist across refreshes.
3 -> 4 is not. Do you have a repro?

**Comment by ddeath** [comment]
Sorry It is private. After some looking into code I guess it will be some configuration error. When it turns out that it is not and I will have some reasonable small example I will post it here.

**Comment by oyeanuj** [comment]
@taion In this case, if one wants the state to be refreshed between 2 -> 3, what should one do? (I'm on RR3 and History 3)?

@ddeath what did you end up finding in your case here?

**Comment by ddeath** [comment]
@oyeanuj sorry I did not.
