### ISSUE TITLE
Upgrading from history 2.0.2 to 2.1.2: error saying we use history 3.x history obj while we use 2.x

### ISSUE THREAD

**Issue by slorber** [ReactTraining/history#333]
Hi,

In my package.json I had:    
 "history": "^2.0.2", 
 "react-router": "^2.0.2", 

At some point it got upgraded on a coworker computer to 2.1.2 for histort and 2.5.2 for react-router, which is valid according to our semver range.

And with these new versions we have this error in our app that we didn't have with previous versions:
`You have provided a history object created with history v3.x. This version of React Router is not compatible with v3 history objects. Please use history v2.x instead.`

Is it a bit confusing because we are not using history 3.x anywhere.

Not a big deal for me, just forcing usage of old versions that I know are working, but maybe some others will get confused by this message.

**Comment by taion** [comment]
You've probably ended up with a v3 history object somewhere. Make sure you actually have the versions of history installed that you think you do.

**Comment by slorber** [comment]
I'm sure I don't have any history 3.x anywhere.

```
sebastien@sebastien-xps:Stample-react (master *$)$ npm ls | grep history
├─┬ history@2.1.2
│ ├── connect-history-api-fallback@1.1.0
sebastien@sebastien-xps:Stample-react (master *$)$ npm ls | grep react-router
├─┬ react-router@2.5.2

```

**Comment by taion** [comment]
We're not hitting this invariant in our test suite, and I'm not hitting it on my pages. Are you adding your own `getCurrentLocation` method or something?

**Comment by slorber** [comment]
yes! :)
I'm enhancing the history object with this exact method name (that I backported from history v3 after @threepointone mention)! 

Sorry for time lost didn't though it could be the problem
