### ISSUE TITLE
SPA on static page or: How to build a queryHistory?

### ISSUE THREAD

**Issue by scharf** [ReactTraining/history#340]
## Requirement: Embedding a Single Page App into a foreign site

I have a SPA that must be hosted as static sites on a servers where I have little control over. 

## Problems with `browserHistory`

In this case, I cannot use `browserHistory`, although it works with the life app, as soon as someone takes the link and shares it, the link does not work, because the server does not know about the link. 

For example: Given the static page `http://example.org/spa.html`, then the path `/foo?page=1` maps to `http://example.org/spa.html/foo?page=1` which causes problems when loaded by the simple static server (it cannot find `/spa.html/foo`)

## Problem: `hashHistory` is a "dead end"

To get this working, I have use `hashHistory`, because the url becomes something like `http://example.org/spa.html#/foo?page=1`, which is fine but it has all the known limitations. Most importantly, I may have to switch the `browserHistory` (to get server side rendering) and then all the old links don't work anymore (see below).

## Solution: `queryHistory`

Instead I'd like to user a `queryHistory` where the path is appended to the query part of the URL: `http://example.org/spa.html?/foo&page=1` or `http://example.org/spa.html?_path=/foo&page=1`. 

### Advantages of `queryHistory`

- If the server gets more clever in the future, I could do server side rendering without changing the url. 
- When I have server side rendering, bots can deal with it, because for a bot an url with different query parameters has to be requested from the server. With the `hashHistory`, the server can never redirect the url (since it does not get the hash part of the url), nor can it do server side rendering.
- In essence: `queryHistory` would allows me to progressively enhance the integration with the server without introducing disruptive changes in the URL schema (there is no need to change form `hashHistory ` to `browserHistory`).

## Questions

- Is there a technical reason or limitations that prevents the use of a `queryHistory` strategy?
- Any advice how to build a `queryHistory`?

**Comment by taion** [comment]
We don't have this sort of history because it's not generally useful – it'd require having the HTML5 history API, but would not create "pretty URLs".

If you want to implement this, for now your best bet is to create a copy of browser history/BrowserProtocol, and sub out the function for calculating the new path based on the location.
