### ISSUE TITLE
Duplicate Basename

### ISSUE THREAD

**Issue by gf3** [ReactTraining/history#343]
I've configured history to have a base of `/embed2` like so:

``` js
const history = useRouterHistory(useBasename(createHistory))({
  basename: '/embed2'
});
```

However, when attempting to push state on the history, `useBasename` is duplicating the base which prevents my routes from matching. You'll notice this behaviour in the screenshot below:

![screen shot 2016-08-03 at 5 20 35 pm](https://cloud.githubusercontent.com/assets/18397/17382447/dd88328c-599e-11e6-9c4f-d9cbcfcac892.png)

* history `2.1.2`
* react-router `2.6.1`

**Comment by taion** [comment]
`useRouterName` includes `useBasename`.

@mjackson BTW, this is another potential advantage of enhancers that work on already-built histories... error conditions with accidentally applying the same enhancer twice end up becoming no-ops.

**Comment by gf3** [comment]
thanks!
