### ISSUE TITLE
Cannot call `history.getCurrentLocation` as demonstrated in the README

### ISSUE THREAD

**Issue by shepmaster** [ReactTraining/history#345]
From [the README](https://github.com/ReactTraining/history/blob/4262ec43182455ff97999423748c0567733f9ffd/README.md):
 
```js
import { createHistory } from 'history'

const history = createHistory()

// Get the current location
const location = history.getCurrentLocation()
```

However, it appears that [`getCurrentLocation` is not defined (JSBin)](http://jsbin.com/qosufoyewi/1/edit?html,js,console)? I've tried a similar inclusion locally with the same result. I'm certain I'm doing something quite stupid, as I can see that [the method is included in the object returned by `createBrowserHistory`](https://github.com/ReactTraining/history/blob/1cf19903572e0230920c71ff7ce2e3e4fd306b15/modules/createBrowserHistory.js#L38).

`history.push` correctly updates the browser URL, so I believe I have the library correctly installed in general.

**Comment by taion** [comment]
Your JSBin is trying to log out `getCurrentLocation` on `window.history` for whatever reason. If you rename the variable to something like `browserHistory`, it works.

More broadly, you're likely seeing this error in "real" code because you have history v2 installed instead of v3.

**Comment by shepmaster** [comment]
Very strange.

```
$ grep history package.json
    "history": "^3.0.0",
$ grep version node_modules/history/package.json
  "version": "3.0.0"
```

However, after restarting my `webpack --watch` command, my local version does indeed work. It must have been picking up some 2.0 version. Thanks for the library and your patience!
