### ISSUE TITLE
Add location.delta

### ISSUE THREAD

**Issue by xpepermint** [ReactTraining/history#36]
Hey. It would be great to know the direction of the transition thus we can set a different animation (with `react-router`) for  forward/back actions. I first though that I can depend on `action` but browser back/forward buttons are always `POP`. I would appreciate if we can add this feature, thx?

**Comment by mjackson** [comment]
I think I'd prefer to have something a bit more general, like `location.delta` that would give us the `n` the user supplied to `go(n)`. When going back, `location.delta` would be `-1`. Likewise, when going forward `location.delta` would be `1`.

**Comment by xpepermint** [comment]
Even better :).

**Comment by ricardosoeiro** [comment]
This would be a great improvement! I'm also relying on location.POP to detect back transitions and perform a different animation, but it is not reliable because of the (less frequent) forward transitions. Is this planned?

**Comment by mjackson** [comment]
I think this would make a great addition to the library, but haven't had time to get to it. I would love it if someone else could step up and take a shot at this. It's a feature that a lot of people seem to want.

**Comment by mjackson** [comment]
This is superseded by #334. If we can figure out how to provide `location.index`, users can derive the delta for themselves.
