### ISSUE TITLE
Stacking multiple block hooks when delaying transitions?

### ISSUE THREAD

**Issue by phyllisstein** [ReactTraining/history#423]
Hey there! I hope this isn't too StackOverflow-y a question, but I've been trying to reimplement some of the functionality of `listenBefore` using `block` and have run into a little trouble.

Previously, I'd had a component that included a `listenBefore` hook like this:

```js
  routerWillLeave(location, cb) {
    const {
      exit: { animation, ...velocityArgs },
      onExit
    } = this.props;

    if (!animation) {
      cb();

      return;
    }

    const childNodes = this.childNodes
      .filter(n => Boolean(n))
      .map(n => findDOMNode(n));

    const { height, width } = this.root.getBoundingClientRect();

    this.setState({ height, width }, () => {
      Velocity(childNodes, animation, { drag: true, stagger: 300, ...velocityArgs }).then(() => {
        if (onExit) {
          onExit();
        }

        cb();
      });
    });
  }
```

The idea was that one could include several of these components in a view with a variety of different animations, which would fire more or less sequentially on transitioning away from the view and block the transition until they were all completed. It worked great with `listenBefore`, largely because the hooks seemed to "stack"---multiple components could define their own hooks, and they'd all be executed before the transition fired.

Trying to implement the same thing with `block`, I came up with this:

```js
  routerWillLeave(nextLocation) {
    const {
      exit: { animation, ...velocityArgs },
      onExit
    } = this.props;
    const { router } = this.context;

    if (!animation) {
      this._unblock();
      router.push(nextLocation);
      return;
    }

    const childNodes = this.childNodes
      .filter(n => Boolean(n))
      .map(n => findDOMNode(n));

    const { height, width } = this.root.getBoundingClientRect();

    this.setState({ height, width }, () => {
      Velocity(childNodes, animation, { drag: true, stagger: 300, ...velocityArgs }).then(() => {
        if (onExit) {
          onExit();
        }

        this._unblock();
        router.push(nextLocation);
      });
    });
  }
```

...which _almost_ works, but only for one of the components in the view. I get a warning indicating that "A history only supports one prompt at a time," only one set of animations fires, and the transition is blocked completely.

I've skimmed the tests trying to find a comparable case and haven't come up with anything, but I'd be eager for any insight you might have into whether there's a path to replicating the old behavior using the current API. Of course, if it's hopeless, I can just stick to the older version.

Thanks in advance for any guidance you can provide, and---again---please forgive me for abusing the GitHub Issues with an implementation question.

**Comment by mjackson** [comment]
When I only included support for one prompt at a time, the thinking was that if someone needed to run more than one check before navigation they could just implement that themselves. For example, you could create your own array of listeners somewhere and then register a single `block` function that checks with those listeners.

It may help to think about it this way: the most common use case for `block` is to prevent navigation with an alert dialog in the UI. Providing built-in support at this level for showing more than one alert leads to bad UX.

Hope that helps :)
