### ISSUE TITLE
createHashHistory and hash key

### ISSUE THREAD

**Issue by GuillaumeCisco** [ReactTraining/history#424]
Hello and thank you for this amazing tool.
I'm trying to migrate my projects from a react-router v3 stack to a react-router v4 stack and so I'd like to use history 4.x. Note I also use react-router-redux for accessing history from my store but I don't think it's important here (Moreover last current version of react-router-redux is not adapted to history v4).

Firstly, I'd like to apologize if it is not the appropriate place to ask this question but I still do not know if I'm doing incorrectly things or is there actually a remaining bug.

I try to test createHashHistory for my development process in order to avoid configuring a development server. I know I could also put a listener on history and build my own redirections for my development needs. Trick that works!

But I came across a weird behavior. I have no more `?_k=` in my url, reading CHANGES.md it seems legacy, so ok ! good ! No more ugly url. But If I browse my website, and hit browser back button it does not work anymore. What am I missing?
Should I create a specific configuration ?

I've put a listener on history to see what's going on when I browse my website, and it seems like only `pathname` and `search` fields are updated. `hash`, `key`  and `state` are not (which seems ok for the last one in a createHashHistory config, but why is it present then?).

Thank you for your time :)

**Comment by mjackson** [comment]
> Hello and thank you for this amazing tool.

You're very welcome :)

The back/forward buttons still work when using hash history, but you're right, you won't have `hash`, `key`, or `state`.

We can only provide `key` and `state` using the `state` argument to `pushState` and `replaceState`, which are part of the HTML5 history API. In past versions of history we tried to mimic this behavior with hash history, but we had to use `sessionStorage` and there were just too many issues with it for us to recommend it generally.
