### ISSUE TITLE
Feature request: Support relative paths in history.push

### ISSUE THREAD

**Issue by mereskin** [ReactTraining/history#428]
Hi! Do you think that would make sense to support relative paths in `history.push`? So we can do stuff like that:

```
browserHistory.push('../'); // go to parent
browserHistory.push('../sibling'); // go to sibling
```

**Comment by mjackson** [comment]
You'll be happy to know that [we already *do* support relative pathnames](https://github.com/ReactTraining/history/blob/22a2f4d31f7bb74027afae8ea624fdb82730e5c5/modules/LocationUtils.js#L38-L45) :)

If you're not seeing this you may be using an older version.

**Comment by mereskin** [comment]
Looks like we are on outdated version. 

We use RR 2.5.3 which uses history ^2.0.1 and there's no LocationUtils there. Looks like there's no way we can get this in v2: v2.8.2 uses history 2.1.2.

Thank you!

**Comment by quanganhtran** [comment]
I have a question related to relative path

When I call `browserHistory.push('posts')`
path e.g. `/user/1` goes to `/user/posts`
path `/user/1/` goes to `/user/1/posts`

It was unexpected to me at first, but then I supposed it might be the correct behavior
Is there a config to always append a trailing slash? Or a way to go to the deeper level from the first path?
In general what would you recommend?

I'm using universal-router, and currently trailing slash doesn't matter in my routes, so `/user/1` and `/user/1/` resolve to the same page
