### ISSUE TITLE
Locked down Mobile Safari throws DOMException on accessing sessionStorage

### ISSUE THREAD

**Issue by q42jaap** [ReactTraining/history#429]
https://github.com/ReactTraining/history/blob/v3.x/modules/DOMStateStorage.js#L18

We're seeing that access window.sessionStorage throws errors for a small fraction of our users, using mobile safari with the following error:
`SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.`

It might be worth it to test for sessionStorage with a try catch arround it...

**Comment by mjackson** [comment]
Sure, we could just move that `if` statement inside the `try` below.

**Comment by mjackson** [comment]
I'm sorry but I can't support version 3 any more. Please send a PR if you'd like to see this fixed.

**Comment by okovpashko** [comment]
I've created #439 with fix for this error
