### ISSUE TITLE
history.getCurrentLocation key differs when calling in server and browser

### ISSUE THREAD

**Issue by michaelBenin** [ReactTraining/history#431]
Originally reported here: https://github.com/reactjs/react-router-redux/issues/528#issuecomment-280062297

`history.getCurrentLocation()`

When called on server yields a key of null and has a key in the browser. 

Can the logic used to create this key be equal in both environments? 

Thank you!

**Comment by mjackson** [comment]
I'm not supporting version 3 any more. Please send a PR if you'd like to get this fixed.

**Comment by michaelBenin** [comment]
Is this fixed in v4?

**Comment by mjackson** [comment]
`history.getCurrentLocation` is gone in v4. Instead, you use `history.location` directly.

In the browser, `location.key` will always be `null` on the initial page load. If you need a key, just use some other constant like "root".

**Comment by michaelBenin** [comment]
OK great, I'll try to update the example on github with latest history/react-router-redux/react-router.

**Comment by michaelBenin** [comment]
@mjackson this is still an issue in v4. The location.key differs from client and server. Should I open a new issue with reproduction case?

**Comment by mjackson** [comment]
@michaelBenin Yes, if you've got a problem with how the code works please open an issue. Even better would be to open a PR with a suggested fix :)

**Comment by michaelBenin** [comment]
Sure thing! Thank you!

**Comment by michaelBenin** [comment]
Hey @mjackson before I add this feature I wanted to ask if I was possibly missing something.

When we call `createHistory` from `browserHistory` how would you feel about passing an initial key there? This would prevent the invariant error I'm finding.

Currently I have this working:

```
const browserHistory = createHistory();
browserHistory.location.key = bootstrappedConfig.routing.location.key;
```

Where bootstrapped config is my redux store from the server. 

It would be great if we could pass createBrowserHistory the key that is generated from the server.

Here is the code on the server which creates that location:

```
const memoryHistory = createMemoryHistory(req.url);
```

**Comment by michaelBenin** [comment]
Moved to an open issue: https://github.com/ReactTraining/history/issues/458
