### ISSUE TITLE
Async transition hooks?

### ISSUE THREAD

**Issue by jeron-diovis** [ReactTraining/history#434]
I'm sorry if I'm duplicating some existing issue about this. 

I found some issues like #50 and related, but they all seems to be about something non-existent in current version of `history`.

At least, currently neither docs nor [code](https://github.com/ReactTraining/history/blob/203bd1ff2ddd1040b52fe2dc9c65bd737b1ddd6e/modules/createTransitionManager.js#L25) says that async check is possible to do things like this: 

```js
history.block((location, action, cb) => asyncValidate(myInput.value).then(cb))
```

Only `getUserConfirmation` accepts a callback – but it works only with confirmation text, so if I need both asynchronicity and current location, I have to access `history.location` through closure. Is this a supposed way to do what I want? And do you have plans to add such feature in future?

**Comment by mjackson** [comment]
`history.block` is a synchronous API. We had an async API in past versions, but it was too buggy so we removed it.

**Comment by jeron-diovis** [comment]
Hmm... but it looks so easy to implement:
```js
if (prompt != null) {
  const promptCallback = result => {
    if (typeof result === 'string') {
      ...all current logic
  }

  typeof prompt === 'function' ? prompt(location, action, promptCallback) : promptCallback(prompt)
```
Is it wrong?

Could you please give some short example about what kind of bugs asynchronicity can bring in this API?
Even if it will never be added, I would like to know what I should be afraid trying to do this.

**Comment by mjackson** [comment]
What's your use case? Also, what happens if the user clicks the back button while you're still in the callback?

**Comment by jeron-diovis** [comment]
If my data are inside some container, like RxJS Observable, how do I access them synchronously in `prompt`?

> Also, what happens if the user clicks the back button while you're still in the callback?
Good question. I don't know, to be honest. But, isn't it true also for callback used in `getUserConfirmation`?

Actually, this is what confuses me a lot. `confirmTransitionTo` API is already async – as it accepts a callback. But `prompt` function is not. Where is the difference?

**Comment by mjackson** [comment]
No I mean what does the user need to do that is async? Getting a confirmation from a user is necessarily async because they need some time to click on the button. But we should be able to block the transition synchronously. The fact that your code won't let you do that just means you need to change your code.

**Comment by jeron-diovis** [comment]
> No I mean what does the user need to do that is async?

User does not need to do anything *to decide whether there are block conditions*. The code does need to do this. And code can be either sync or async. User only *decides whether to agree* with that conditions. Talking about `prompt` function we're talking only about code, not about interaction with user, do we?

> The fact that your code won't let you do that just means you need to change your code.

Well, it's a strong argument =)
I agree. But please, explain what do you mean under "block the transition synchronously"? 
I really don't understand this point. Looking at code, I see that the transition handling process consists of:
* calling `history.push` – it's sync, ok
* calling `transitionManager.confirmTransitionTo` – still sync
* executing code in callback, passed to `confirmTransitionTo` – and in case of custom `getUserConfirmation` function this operation can be async. So entire process of blocking transition is potentially async. And so, I'll repeat myself, yet another callback on the way does not make any difference.

**Comment by jeron-diovis** [comment]
Any updates?

**Comment by mjackson** [comment]
No. This issue is closed, meaning I don't intend to do anything. If you'd like to make a change, I'd be happy to consider a PR. But I'm fine with the current API.

**Comment by jeron-diovis** [comment]
@mjackson I mean what about my [question above](https://github.com/ReactTraining/history/issues/434#issuecomment-280773416)?

It would be glad to make a PR, but you insist that making `prompt` function async will break ability to "block the transition synchronously" – whatever this means. 
So, until I understand this, there is no sense to submit something that is definitely wrong for you.
