### ISSUE TITLE
Push/replace with only a hash shouldn't clear the search

### ISSUE THREAD

**Issue by aij** [ReactTraining/history#443]
I would expect `push` and `replace` to support relative URLs, like `window.location.replace()` and assign do.

Currently, a relative URL starting with a path works. Starting with a query string also works. Starting with a hash only works if it is being resolved relative to a location that does not include a search/query string. Otherwise it get set to the empty string rather than being preserved.

For example, compare the behavior of `window.location = '#foo'` and `window.location.replace('#bar')` with the behavior of `history.push('#foo')` and `history.replace('#bar')'.

I'll send a PR with tests showing what works and what doesn't.

**Comment by StringEpsilon** [comment]
I can't reproduce this in history version 5.

**Comment by aij** [comment]
And I'm not longer using this library, so I'll  go ahead and close it assuming no one still cares to maintain the  3.x series.
