### ISSUE TITLE
Deprecated history object to <Router/>

### ISSUE THREAD

**Issue by DonikaV** [ReactTraining/history#446]
import { Router, Route, useRouterHistory, DefaultRoute} from "react-router";
import createHistory from 'history/createBrowserHistory';

const history = createHistory({
    basename: '/'
});

<Router history = {history} path='/'>
</Router>

Warning: [react-router] It appears you have provided a deprecated history object to `<Router/>`, please use a history provided by React Router with `import { browserHistory } from 'react-router'` or `import { hashHistory } from 'react-router'`. If you are using a custom history please create it with `useRouterHistory`, see http://tiny.cc/router-usinghistory for details.

Hi, i try ti find problem about push. I updated 'history' package, earlier it was

const history = useRouterHistory(createHistory)({
  basename: '/'
});
Why i see errors?
Thanks.

**Comment by jarecsni** [comment]
Just upgraded to 4.6 and I got an error from a React component saying _this.props.history.location: can't get 'location' of undefined (something along these lines). I've downgraded to previous version and the error is gone. To be honest, there were a couple of other artefacts upgraded, but those seemed quite unrelated. I can try to retrieve exact error if that'd help.

**Comment by mjackson** [comment]
It looks like you're using a really old version of history and react-router. Please update.

**Comment by jarecsni** [comment]
As I said, it is happening after upgrading to latest version of all deps: "history": "^4.2.0", "react-router": "^4.0.0". It is working fine with older versions: "react-router": "^3.0.0". Hm actually history wasn't exactly upgraded, it was 4.2.0 before. So it seems to be a react-router issue.

**Comment by jarecsni** [comment]
Well I can't really tell if it's an issue for react-router or history, it seems what used to work with react-router 3.x no longer works on 4.x
