### ISSUE TITLE
Deprecate location.action

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/history#449]
There aren't really any great use cases for this, so we should deprecate and remove it.

**Comment by smashercosmo** [comment]
What are the drawbacks of not removing it?

**Comment by mjackson** [comment]
Main drawback is that people come to rely on it, which could be a bad thing since it's not always accurate, especially when using hash history.

**Comment by taurose** [comment]
I recall some people using it for animations.

When is it not accurate exactly?

**Comment by mjackson** [comment]
Well, with hash history specifically [we always just use `POP`](https://github.com/ReactTraining/history/blob/a647c5d1e5442998855700195b80a8a60b7f7656/modules/createHashHistory.js#L127) on `hashchange`. So it's not accurate at all. I tried to add support for `PUSH` and `REPLACE` but since all location changes to through `hashchange` it's tricky because you have to wait for the browser to emit `hashchange` and somehow recognize it was caused by your most recent `push`.

I seem to recall some people were doing stuff with `action` a long time ago too, but after using the router for a few years I don't see anyone doing it these days. None of our examples use it.

**Comment by taurose** [comment]
The `hashchange`s from push&replace are ignored though due to the locations being equal to the ones already set by push&replace. I see it would be easier without `action`, but it should be accurate, shouldn't it?

Isn't it also required for manual scroll management? Also, there is an [example that uses it](https://reacttraining.com/react-router/web/example/modal-gallery).

**Comment by mjackson** [comment]
I honestly don't know how accurate that code is. Some browsers fire `hashchange` more than once for a single change.

On second thought I guess we can just keep it. It's a weird little piece of API and I'm not 100% convinced there's actually a good use case for it, but maybe there is.
