### ISSUE TITLE
specifying basename not taking effect

### ISSUE THREAD

**Issue by kimasendorf** [ReactTraining/history#451]
I have 2 React SPAs running, one in the root and one in a subfolder. I have successfully migrated the root app to react-router-dom v4. Both apps have the same structure but still I am not able to get the `basename` prop working in the subfolder app.
```
const history = createBrowserHistory({
  basename: '/subapp'
});
```
This does not work. It gets simply ignored.

Any ideas?

**Comment by kimasendorf** [comment]
I was able to get the basename working when I add it to the router as attribute.

`<Router basename="/subapp" history={history}>`

**Comment by mjackson** [comment]
We'd need to see some more code to tell you why this isn't working for you. `<Router basename>` isn't even part of our API.

**Comment by kimasendorf** [comment]
Yeah, it is obviously a react-router issues. Sorry.
