### ISSUE TITLE
v3.3.0 - URL restoration on canceled popstate transitions

### ISSUE THREAD

**Issue by amangeot** [ReactTraining/history#454]
Hello,
I believe there is an issue with URL restoration on canceled popstate transitions. It works perfectly unless we cancel the first transition after a page refresh with an existing browser history.

When such case happens, the transition is blocked, the app route does not update, but the navigator url bar displays the previous location.

---
My use case is to block transitions with `listenBefore` when a popup is open, to close the popup instead of transitioning.

```
import { browserHistory } from 'react-router'
import { syncHistoryWithStore } from 'react-router-redux'

// ...
const store = createStore(initialState, browserHistory)
const history = syncHistoryWithStore(browserHistory, store)
history.listenBefore(popupTransitionListener(store))
```

```
const popupTransitionListener = (store) => (location) => {
    const shouldClosePopup = test(store)
    // Close popup if open

    const shouldBlock= shouldClosePopup && location.action === 'POP'
    if (shouldBlock) return false
  }
}
```
Latest version of Chrome on Windows 10
react-router: v3.0.2
history: v3.3.0
react-router-redux: v4.0.8

**Comment by mjackson** [comment]
Hi @amangeot, thanks for reporting the issue. Unfortunately there were some issues with the 3.x releases. We don't intend to fix them in the 3.x branch, but we haven't had any similar issues with 4.x. Please update as soon as you are able. Thanks.
