### ISSUE TITLE
Redirect using history in actioncreator and react-router v.4

### ISSUE THREAD

**Issue by maxdonetsk** [ReactTraining/history#457]
Hi, I'm trying to navigate programmatically in action creator after calling an API and receiving a response.
What I did:
I created a file utils/History.js with this code:
`import createBrowserHistory from 'history/createBrowserHistory';
export default createBrowserHistory();`

and then used it in action creator:
`import History from '../../utils/History';
//some code//
History.replace('/sign-in');`
Of course, I let relevant component know about this routing. If I use `<NavLink to='/sign-in'>,` it works.
But if I want to render this component on History.replace('/sign-in') or History.push('/sign-in'), I can see just 'localhost:8080/sign-in' in addressbar, but relevant component doesn't appear.
Please help me to figure out.

**Comment by crapthings** [comment]
i've the same issues
navigate programmatically is difficulty in v4

because someplace we can't get props.history

<Router history={history} /> doesn't work for me either.

**Comment by maxdonetsk** [comment]
I've got it to work with conditional rendering (passing a flag to `this.state`), but this is obviously not a React way and not a best practice...

**Comment by taurose** [comment]
Seems more like a react-router question.

You don't want to use two history instances in parallel. If you need to access the history instance outside of react-router's `<BrowserRouter>`, I think the cleanest solution is to use `<Router>` directly. Here's the docs: https://reacttraining.com/react-router/web/api/Router

**Comment by maxdonetsk** [comment]
@taurose Thanks for answer. I can use `<Router>` inside a component. Is there a way to use it in action creator?

**Comment by maxdonetsk** [comment]
Solved here:
https://github.com/ReactTraining/react-router/issues/4895
