### ISSUE TITLE
Release latest v3 commit

### ISSUE THREAD

**Issue by Cavitt** [ReactTraining/history#462]
Could you please release the sessionStorage fix (https://github.com/ReactTraining/history/commit/a6f8d635311fde98f27aae45d62f65b3140277bd)
under the v3 branch to NPM.

**Comment by okovpashko** [comment]
@mjackson there's still no NPM release for this fix. Could you please do it? We still use history v3 because it's a dependency of react-router v3 and we can't upgrade to react-router v4 because of major API changes.

**Comment by mjackson** [comment]
Sorry, but I don't have the bandwidth right now to maintain v3. If you need the patch, please go ahead and fork away. But v4 is more than 2 years old at this point.

**Comment by okovpashko** [comment]
It's a bit strange that there were PR's with fixes merged to v3 branch but they weren't published to NPM ¯\_(ツ)_/¯
