### ISSUE TITLE
A Question : Why doesn't HashRouter support state?

### ISSUE THREAD

**Issue by vifird** [ReactTraining/history#463]
Have readed the code of history, but can't understand why HashRouter doesn't support state. In BrowserRouter it's supported, and it seems that it can be done in HashRouter just as in BrowserRouter, and i can easily get it done by changing little code(As i have did).
I think there must be some reason, but i can't think it out.

**Comment by mjackson** [comment]
I think we can support state in hash history, but only in browsers that also support `pushState`. It hadn't occurred to me that people might want to do this when I was working on history v4, but I'd love to discuss how we can refactor things to make it possible in some future version of the library.

**Comment by matthewrobb** [comment]
Just wanted to add a comment. What I think can be supported is not state in HashRouter rather it would be to support hash routing in BrowserRouter.

**Comment by vifird** [comment]
@matthewrobb hash routing in BrowserRouter? not HashRouter?

**Comment by vifird** [comment]
@mjackson Thanks. I found it's supported in v3, but it need random key in url, and i changed some code to delete key in some browsers that support state API(auto use key when state API is not supported).
URL: [Vifird history](https://github.com/vifird/history)

**Comment by matthewrobb** [comment]
@vifird Yeah, check this out: https://github.com/ReactTraining/history/issues/435#issuecomment-287853906
