### ISSUE TITLE
createHref doesn't work when called with a string

### ISSUE THREAD

**Issue by arolson101** [ReactTraining/history#464]
AFAICT history.createHref is supposed to be able to take a string and not just a location object.  When I call with a string (e.g. ```history.createHref('/a/b')```) I get an exception because in ```createPath``` it caches ```location.search``` which is the function String.search(), causing the ```search.charAt(0)``` to throw an exception

**Comment by mjackson** [comment]
No, the signature is `createHref(location)`. Any time you read the word `location` in the code/docs it means an object in roughly the same shape as `window.location`, e.g. `{ pathname, search, hash }`.
