### ISSUE TITLE
[v3&v4] history.listen is not triggered when refresh page 

### ISSUE THREAD

**Issue by ximing** [ReactTraining/history#466]
```
import { createHistory } from 'history'
const history = createHistory()
// Listen for changes to the current location.
history.listen((location, action) => {
    console.log('ok')
})
```

When I refresh the page ，v2 will output 'ok'，but  v3&v4 will not。

**Comment by mjackson** [comment]
`history.listen` only works on a single page, not across page refreshes. The whole purpose of the history library is for building single page apps.

**Comment by ximing** [comment]
For a single page application， I think it's necessary When I want to do something after the page first loaded。   For exmaple ，according to different routes，send request to different APIs. 
Of course,  I could do this in window.onload event ,but I have to write it again in history.listen so that I can handle the situation that user change router from a to b in SPA. 

So I think it's necessary to trigger history.listen when page loaded。
