### ISSUE TITLE
history.block does not work in iOS Safari

### ISSUE THREAD

**Issue by nickersonr** [ReactTraining/history#471]
Sometimes you want to be able to intercept/block route changes with .block (and react-routers Prompt component with message=false). Unfortunately, this does not work in iOS safari, it works in Chrome just fine. Before, react-router would use setRouteLeaveHook, but that no longer exists, and the people over at react-router said to use history.block, but it is not working in iOS Safari.

**Comment by mjackson** [comment]
Can you please show an example of how you're using it? [This test](https://github.com/ReactTraining/history/blob/master/modules/__tests__/TestSequences/BlockEverything.js) should give you an idea of how it is supposed to be used. We currently run that test (and it passes!) [in iOS 8.3 and 9.1](https://github.com/ReactTraining/history/blob/632dd9b91a3f7572596fd2f63bd8a8708c317c47/karma.conf.js#L27-L40).

**Comment by steven-luu** [comment]
Is it possible you could run the test suite for iOS 10.x?

I'm seeing the same thing as @nickersonr . Usage should be correct as it is working in other browsers.  Also working on desktop Safari Version 10.1.1   
(I don't have a device with iOS 8.3 or 9.1 to see what you're seeing)

**Comment by pshrmn** [comment]
As Michael stated, an example of a `history.block` call that does not work would be very useful here. It is difficult to diagnose an issue based on "it is not working".

I _think_ that you could open a PR that adds iOS 10.x to the [Karma configuration](https://github.com/ReactTraining/history/blob/master/karma.conf.js) and it should run the tests on that. The test suite is pretty exhaustive, so in theory one of the tests should catch this issue, but if not, it should be fairly easy to add a test using the previously requested example .

**Comment by steven-luu** [comment]
Here's my screen with the relevant pieces.  Is this sufficient? 

```
import React, { Component } from 'react'

export default class TestHistoryBlock extends Component<{}>{
  private historyBlocked: () => void

  constructor(props) {
    super(props)

    this.historyBlocked = props.history.block(this.shouldBlockBack.bind(this))
  }

  shouldBlockBack(location, action) {
    const shouldBlock = true
    if (shouldBlock) {
      return 'Some text about being blocked'
    }

    // [browser-compat] Don't return anything if we shouldn't block
    return
  }

  componentWillUnmount() {
    this.historyBlocked && this.historyBlocked()
  }

  render() {
    return <span style={{ color: 'white' }}>React router block test</span>
  }
}
```

I currently am on this version:
react-router: 4.1.1

I started reading about the Karma config linked and BrowserStack, but I'll continue tomorrow as it's getting late here.

**Comment by k3ntako** [comment]
Are there any updates on this?
