### ISSUE TITLE
Why accessing https://github.com/ReactTraining/history/commits/master give a 500

### ISSUE THREAD

**Issue by d6u** [ReactTraining/history#476]
IDK if this is related to repo setup or github, but where can I find the commit history? I found a strange behavior in ReactRouterDOM (v4), that related to how `createPath` function is calling encodeURI before it returns, but I cannot find the code anywhere in this repo 😓

**Comment by pshrmn** [comment]
Probably related to #461 and #465

**Comment by mjackson** [comment]
I'm not sure what the original problem was here but it seems to be ok now.
