### ISSUE TITLE
history.listen never fires

### ISSUE THREAD

**Issue by ilyador** [ReactTraining/history#479]
Switched to router v4 and history v4.5.1 and now history listener not working

```
import createBrowserHistory from 'history/createBrowserHistory'
const history = createBrowserHistory()

history.listen((location, action) => {
  console.log(action, location.pathname, location.state)  //  <=== Never happens
})

render(
  <Provider store={store}>
    <Router history={history}>
      ...
    </Router>
  </Provider>,
  document.getElementById('root')
)
```
Any ideas why it is being ignored?

**Comment by mjackson** [comment]
`history.listen` only fires when the location changes. On the initial page load, the current location is already in `history.location`.

**Comment by sdeleon28** [comment]
I think @ilyador meant it doesn't get fired (ever). I'm trying to use this same approach to follow how the path changes in a React Native environment. I can click on `Link`s all day long and see no output on the console. In case it makes a difference, my code is pretty much the same, only using `createMemoryHistory`.

**Comment by ilyador** [comment]
@mjackson As @sdeleon28 said, it never fires, not just on initial page load.

**Comment by mschmidt712** [comment]
I'm having this same issue. I can log the history object and see that it was created correctly but the listener never fires when I route between views. I am loading and configuring the history object in my index.js file like so.

```
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import createHistory from 'history/createBrowserHistory';
import App from './components/App';

const history = createHistory();
const unlisten = history.listen((location, action) => {
  console.log(action, location.pathname, location.state)
});

ReactDOM.render(
  <BrowserRouter>
    <App />
  </BrowserRouter>, document.getElementById('root'));
registerServiceWorker();
```

and my App component looks like so 

```
import React, { Component } from 'react';
import { BrowserRouter, Route } from 'react-router-dom';
import Header from './Header';
import './App.css';

import Home from './Home';
import Static from './Static';

class App extends Component {
  render() {
    return (
      <div className="App">
        <Header />
        <BrowserRouter>
          <div>
              <Route exact path="/" component={Home}/>
              <Route path="/help" component={Static}/>
          </div>
        </BrowserRouter>
      </div>
    );
  }
}

export default App;
```

I'm not sure what i am doing wrong here. Any help would be greatly appreciated! I'm running the following versions: 
`"react-router-dom": "^4.1.2" `
`"history": "^4.6.3",`

**Comment by mschmidt712** [comment]
My issue here was using `<BrowserRouter />` instead of the standard `<Router />`. The solution is well described in [this SO post](https://stackoverflow.com/questions/44095744/react-router-4-history-listen-never-fires).

**Comment by yijingping** [comment]
@mschmidt712 this works for me！ thanks
