### ISSUE TITLE
Adding a % in the url causes error

### ISSUE THREAD

**Issue by michaelBenin** [ReactTraining/history#481]
Examples:

https://reacttraining.com/796226/yo%u-dont

**Comment by michaelBenin** [comment]
Open for a try catch here? https://github.com/ReactTraining/history/blob/master/modules/PathUtils.js#L33

**Comment by pshrmn** [comment]
The issue with the example URI that you provided is that it is not valid. The literal percent characters [must be encoded](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_the_percent_character). There is some related discussion in #461.

**Comment by michaelBenin** [comment]
handling here: https://github.com/ReactTraining/history/pull/465
