### ISSUE TITLE
hashhistory v3 history.listen calls the callback synchronously once

### ISSUE THREAD

**Issue by lama-pacos** [ReactTraining/history#482]
### code
```
import { createHashHistory } from 'history'

const history = createHashHistory();

history.listen((location) => {
  console.log(location)
})
```

#### hash change
```
xxx/xxx => xxx/xxx/#/
```

### reason
```
  if (path !== encodedPath)
    replaceHashPath(encodedPath)

  addEventListener(window, HashChangeEvent, handleHashChange)
```

`window.location.replace` is an asynchronous functions. so when it's done. handleHashChange while be triggered.

**Comment by mjackson** [comment]
We fixed this in v4. Now you just read `history.location` immediately and the `listen` callback only fires when the location actually changes.
