### ISSUE TITLE
support for promise-based block?

### ISSUE THREAD

**Issue by moonforeshot** [ReactTraining/history#483]
I'm thinking about customizing block operations on a per-individual basis.
For example, one part of code requires Auth API promise, another would require Item API promise.

What do you think about supporting individual-level customizable block API?

Example code:

```javascript
history.block(async (location, action) => {
     ...
     try {
         const loggedIn = await getLogin( ... );
         return true;
     } catch { return false; }
})
```

Moreover, it might be better to have a generalized 'customized-catch-and-redirect':

```javascript
history.beforeChange(async (location, action, callback) => {
   
    const userLevel = await getUserLevel( ...);
    if (userLevel == "admin") { 
         return location
    }
    else if (userLevel == "user") { 
         return modifiedLocationForNotAdmins; 
     }
     else {
          return false; //block.
     }
});
```

**Comment by mjackson** [comment]
Sure, I'd be open to including support for promises in the blocking API. Just needs a PR.
