### ISSUE TITLE
confirmTransitionTo prompt require type string, maybe it shouldn't?

### ISSUE THREAD

**Issue by fernandojbf** [ReactTraining/history#489]
Hi all,

This may not make sense but maybe we could pass `prompt` as an Object? With this we can configure different outcomes of the `getUserConfirmation` function. Any thoughts about this or does it not make any sense?

Cheers

**Comment by TimoSta** [comment]
We are facing the same issue right now.

We'd like to have a multi-option confirmation popup (save/discard/cancel) and need a way to pass additional details about the actions, and an action handler into `getUserConfirmation`. This is currently not possible.

Any thoughts on this? More than happy to submit a PR if there is interest.

**Comment by mjackson** [comment]
We are removing `history.block` (it's buggy, see #690), so this won't be an issue for us anymore.
