### ISSUE TITLE
Uncaught Error: Cannot find module "history/createBrowserHistory"

### ISSUE THREAD

**Issue by Mmzer** [ReactTraining/history#494]
This is my es6 code:

```javascript
import React, { Component } from 'react';
import createHistory from 'history/createBrowserHistory';

const history = createHistory({
    hashType: 'slash'
});

const ConnectHistory = (WrappedComponent) =>
	class extends Component {
	  render() {
            return <WrappedComponent {...this.props} history={history} />;
	  }
};

export default ConnectHistory;

```
history version:
![image](https://user-images.githubusercontent.com/9158841/27172474-038d993a-51e8-11e7-8c32-b9e0081cc0c6.png)

config with webpack2 and npm@5.0.3

build my project, I got this:

![image](https://user-images.githubusercontent.com/9158841/27172585-59b1a39c-51e8-11e7-83c6-6cfaf651d437.png)

What's wrong?

**Comment by mjackson** [comment]
You're using history version 1. Try version 4.
