### ISSUE TITLE
Functions in DOMUtils blow up if window is undefined

### ISSUE THREAD

**Issue by adamshone** [ReactTraining/history#496]
`supportsPopStateOnHashChange`, `supportsGoWithoutReloadUsingHash` etc all fail in headless mode. I think they just need to check `canUseDOM` before accessing the window.

**Comment by mjackson** [comment]
They're called DOM utils for a reason ... they require a DOM.

**Comment by adamshone** [comment]
Then why do they include a function `canUseDOM`, which clearly does not require a DOM?

At the moment some of the functions in `DOMUtils` can be safely called without a DOM and some cannot, and there is no way to tell which is which without reading the code. Seems like better semantics to just make them all safe.

**Comment by mjackson** [comment]
Why are you trying to use these functions in a non-DOM environment? They're not even [public API](https://github.com/ReactTraining/history/blob/master/modules/index.js).

**Comment by mjackson** [comment]
Ah, just re-read the OP. You're running history in a headless browser. Aren't you supposed to have access to the DOM in headless mode?

**Comment by adamshone** [comment]
These are unit tests running in Node via Mocha. I could include `jsdom` or equivalent, but would rather not - we have a lot of tests and it hasn't been necessary so far.

**Comment by mjackson** [comment]
I'd rather not make this change. The assumption is that if you're using `createBrowserHistory` or `createHashHistory` that there is a DOM available.

If anything, we should probably `throw` when someone tries to use either of those functions w/out a DOM. At least then we can fail a bit faster.
