### ISSUE TITLE
After history.push always scrolling to top

### ISSUE THREAD

**Issue by jaydenlin** [ReactTraining/history#499]
Is there anyway to prevent  scrolling to top after history.push ?
I am using the `createBrowserHistory`.
Thank you in advance.

**Comment by paolomangiadev** [comment]
how funny, i'm looking for a way to scroll to top after every history location change... :D

**Comment by jaydenlin** [comment]
Is there any way to solve the issue ?

**Comment by pshrmn** [comment]
`history.push` shouldn't be scrolling. If you take a look at [the source](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L154), it is just calling `window.history.pushState`, which does not affect the scroll position.

**Comment by GuilhermeMedeiros** [comment]
https://github.com/taion/scroll-behavior

**Comment by mjackson** [comment]
This is probably due to the fact that you're removing all content from the page before putting something in again, causing the browser to scroll to the top.
