### ISSUE TITLE
In IE9, history.push(location.path, {some: state}), it will be refresh

### ISSUE THREAD

**Issue by lemonleon** [ReactTraining/history#500]
I just want push some data, like this
```javascript
const unlisten = history.listen((location, action) => {
            // location is an object like window.location
            console.log(action, location.pathname, location.state)
        });

setTimeout(() => {
            history.push('/test', { some: 'state' })
        }, 2000)
```
location: localhost/test
In IE9, it will be unlimited refresh, I just want push some data, so what should I do? (in IE9)

**Comment by pshrmn** [comment]
You can only attach state to locations when you are in a browser with HTML5 `history` support. IE9 does not support the HTML5 `pushState`/`replaceState` API. That means that `history` has to go into fallback mode, which will relies on `window.location.href = ___` and `window.location.replace` for updating the URI.

You can see support for the `history` API here (click the `Show all` button) http://caniuse.com/#feat=history

**Comment by lemonleon** [comment]
well, thx :)
