### ISSUE TITLE
Push a path with hash won't trigger CSS :target selector

### ISSUE THREAD

**Issue by shuboc** [ReactTraining/history#503]
Say I have an HTML element with an id as follows:

```
<div id="some-hash" />
```

I'd like to add some styles to the div with CSS `:target` selector when it is clicked:

```
:target {
  background: yellow;
}
```

However, If I push a new path with hash to `history` object as follows, `:target` selector won't be triggered on the div:

```
history.push('/page#some-hash')
```

If I just change the URL, `:target` selector works perfectly:

```
window.location.href = 'page#some-hash'
```

I checked the source and it calls `window.history.pushState` with the new URL when history API is available, which doesn't seem to trigger the `:targer` selector.

I am wondering if there is a way to solve or workaround this problem? Thanks in advance.

**Comment by pshrmn** [comment]
According to this thread [0] (and some others that it links to), this behavior is consistent across all browsers. The fact that clicking the browser's back/forward buttons will trigger an update of the `:target` element sounds like this is definitely a bug and not the desired behavior. If not a bug, then it is at least poorly defined behavior. Unfortunately, this does not seem like it will get changed any time soon and I don't think that there is a good way to get around this.

While not a satisfying solution, the way that I would approach this would be to:

1. Listen for location changes
2. Check if the new location object has a `hash` property
3. If it does, check if there is a DOM node with that id
4. If an element with the id exists, give it a `target` class to style it

There are also potential timing issues with this where you would need to delay this until after you are sure that your DOM has rendered. As I said above, this isn't nearly as convenient as `:target`, but it seems to be all that you can really do right now :man_shrugging: 

[0] https://bugs.chromium.org/p/chromium/issues/detail?id=89165

**Comment by shuboc** [comment]
@pshrmn Thanks for your super quick response!

Actually, I found this weird behavior when using `Link` component from React Router.

I found a way to work around this for now:

```
<Link 
  to='/page#some-hash'
  onClick={() =>
    window.location.hash = '#some-hash'
  }
/>
```

It will trigger `:target` selector for anchors in the same page. (Haven't tested it thoroughly.)

I will try your suggestion for anchors across pages. Thanks.
