### ISSUE TITLE
location.toString() returns an empty object

### ISSUE THREAD

**Issue by iansu** [ReactTraining/history#504]
I'm using `history.listen()` to log route changes and I'm trying to get the pathname, search and hash (basically everything in the address bar after the domain name) and was hoping that calling `location.toString()` would give me that. Instead it appears to just return an empty object.

**Comment by mjackson** [comment]
I kind of want to keep `location` objects as simple as possible so we don't have to treat them specially all over the place. That said, creating the string should never be more complex than `location.pathname + location.search + location.hash`.
