### ISSUE TITLE
why 4.7.x not compile import to require?!

### ISSUE THREAD

**Issue by wssgcg1213** [ReactTraining/history#513]
https://unpkg.com/history@4.7.1/createBrowserHistory.js

line 5 

import can not be exec in browser

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/29605763-c0143f24-87b1-11e7-917c-8361d0cf2da5.png)

**Comment by wssgcg1213** [comment]
WaIT ONLINE

**Comment by imsobear** [comment]
+1 for this issue

![image](https://user-images.githubusercontent.com/2505411/29606506-13f835f4-8821-11e7-9bff-51b789b1f32b.png)

**Comment by mjackson** [comment]
Sorry everyone, bad release. That'll teach me to release late at night... it's fixed in 4.7.2

**Comment by wssgcg1213** [comment]
thanks!

**Comment by Nimelrian** [comment]
Thanks for the quick fix, was wondering why all of our builds using react-router-dom started failing.
