### ISSUE TITLE
Browser back button click is not being stopped by block 

### ISSUE THREAD

**Issue by elijah1210** [ReactTraining/history#524]
Hi,
I have the following section of code in my component.
```
this.props.history.block((location, action) => {
	// Browser action (forward, back) is a pop action, if data has been modified, show custom prompt when they attempt to do so.
	if (action === 'POP' && this.props.hasDataChanged) {
		// Confirm with user.
		return 'Are you sure you want to continue?';
	}

	// No need to confirm with user.
	return null;
});
```
However, when I click the back button, it moves to the previous location, and then the prompt is shown, clicking no brings me back to the original route but it does trigger a location change which I handle in the middleware.

**Comment by pshrmn** [comment]
`history` cannot catch `popstate` events before they happen. All that it can do is to identify that they occurred and revert to the previous location if the user cancel's the navigation.

**Comment by elijah1210** [comment]
Do you know of anything off the top of your head that would give me that functionality?
If not, it's also okay.

**Comment by mjackson** [comment]
Only thing you could try is hooking into the window's `beforeunload` event. But that has its own caveats, like enabling BFCache in Firefox.
