### ISSUE TITLE
Feature Request: Replace State on PopState

### ISSUE THREAD

**Issue by ccorcos** [ReactTraining/history#529]
Carried over from https://github.com/ReactTraining/react-router/issues/5562

In older versions of History, the route state was held in a local cache and only a key was saved in actual browser route state. The benefit of this approach was that I was able to effectively replace the state of a route on the popstate event without preventing the browser from changing routes.

This was particularly useful for saving scroll position before leaving a page. It would be great if there were some way to do this again.

**Comment by mjackson** [comment]
We can't store history state in session storage anymore like we used to do because it is unreliable. It's not even available in some scenarios, like private browsing. But `history.state` is, so that's what we use now.
