### ISSUE TITLE
"Hash history cannot push/replace state; it is ignored". history.push/replace doesn't have second param

### ISSUE THREAD

**Issue by lqs469** [ReactTraining/history#530]
When I use history function push/replace. that's what written in the [API](https://github.com/ReactTraining/history#navigation).
```
- history.push(path, [state])
- history.replace(path, [state])
```
And example:
```
// Push a new entry onto the history stack with a query string
// and some state. Location state does not appear in the URL.
history.push('/home?the=query', { some: 'state' })
```
But when I use it in the code. Error likes this:
![46e2b4f6-b654-410a-8201-699241a85420](https://user-images.githubusercontent.com/6779082/31324097-94204e48-ac74-11e7-906b-5e160e2f042f.png)
and
![3e4710c3-2f1d-45a7-8383-5a1c9b545dc0](https://user-images.githubusercontent.com/6779082/31324103-9ed2b682-ac74-11e7-9595-1a9f8920d7b9.png)

So, I read the source code, found it:
![3c740968-cdbc-4f9a-8366-37ba2749f636](https://user-images.githubusercontent.com/6779082/31324107-b1306cb6-ac74-11e7-8117-4af8cb389900.png)

....oops, Is it wrong with the API? 🤔

**Comment by tech4him1** [comment]
I'm wondering exactly what this error is caused by, could someone provide an explanation?

**Comment by mjackson** [comment]
We only support the `state` argument when using browser/memory history, not hash.

**Comment by w33ble** [comment]
For anyone else looking for a solution to using the History API and hash-based routing and landing here, have a look at [this comment](https://github.com/ReactTraining/history/issues/435#issuecomment-287849591).

**Comment by lqs469** [comment]
@w33ble Thx!
