### ISSUE TITLE
Typescript error in DOMUtils.d.ts?

### ISSUE THREAD

**Issue by anyong** [ReactTraining/history#534]
With the following dependencies:

```
@types/history@4.6.0
history@4.7.2
typescript@2.5.3
```

I get the following typescript error:

`node_modules/@types/history/DOMUtils.d.ts(3,81): error TS2304: Cannot find name 'EventListenerOrEventListenerObject'.`

I also have `"lib": ["dom", "es2017"]` set in `tsconfig.json`. This name exists in `node_modules/typescript/lib/lib.dom.d.ts` - why would it not be picked up by @types/history?

**Comment by mjackson** [comment]
We don't maintain `@types/history` in this repo.
