### ISSUE TITLE
History.replace always creates a new key in sessionStorage (version 3)

### ISSUE THREAD

**Issue by EloB** [ReactTraining/history#540]
I have a problem with the history always creating a new item in the session storage on `history.replace` even if I pass the previous `key`. This will result in a storage exceed limitation issue after some usage. Is there any reason why it creates a new session item instead of overwriting the previous session item? Is this as intended or it's it a bug?

Here is an example and you can look at the sessionStorage getting bigger and bigger.
http://jsbin.com/doyixusuvu/edit?js,console,output

**Comment by mjackson** [comment]
This is intended behavior. The key is unique to each location object.

**Comment by EloB** [comment]
So the intended behavior is to fill the `sessionStorage` until it breaks?

**Comment by mjackson** [comment]
No. We already stopped using sessionStorage in v4. I don't currently maintain v3.

**Comment by JitendraThakur007** [comment]
leave this comment at this time
