### ISSUE TITLE
v4 have no useQueries method like v3

### ISSUE THREAD

**Issue by zhupillow** [ReactTraining/history#552]
i need control the query object on history  while v4 cant handle anymore，i noticed v3 has the ‘useQueries‘ method，but none in v4，i just wanna， can you please add something like ‘useQueries’ in v4 ？ ths。

**Comment by mjackson** [comment]
Please see [my earlier comments on this issue](https://github.com/ReactTraining/history/issues/364#issuecomment-246751904).
