### ISSUE TITLE
Lose window.history.state after page refresh

### ISSUE THREAD

**Issue by vchibilisco-convey** [ReactTraining/history#557]
Hi.

I do not know if a problem in the history library or browser, but ...

I am working on Firefox Quantum 57.0.4 64 bit, and when I select the url and press enter, after updating the page I can not get the history.location.state. After investigating, I discovered that window.history.state is null.

Does anyone have this error?

**Comment by mjackson** [comment]
We need more info in order to help you debug this. Can you show a small, reproducible test case?

**Comment by ImanMh** [comment]
I have the same issue. It's very clear and I'm not sure this package can do anything about it. if you do this: 
```
  history.push('/home', { some: 'state' })
```
when you go to ```home``` you have ```some === 'state'``` and if you refresh in chrome you get that state again which is stupid. In Firefox, things are different and a refresh is counted a fresh new start and you don't have that state which I think is much better. In chrome you have to close the tab and open a new one to get ride of that state.
