### ISSUE TITLE
block and location_change event

### ISSUE THREAD

**Issue by BetterCallSky** [ReactTraining/history#562]
```
"history": "^4.7.2",
"react-router": "^4.2.0",
"react-router-redux": "^5.0.0-alpha.9",
```

```jsx
import createHistory from 'history/createHashHistory';
const history = createHistory();

history.listen((location, action) => {
  console.log(
    `The current URL is ${location.pathname}${location.search}${location.hash}`
  )
  console.log(`The last navigation action was ${action}`)
})


history.block((location, action) => {
  if (foo) {
      console.log('BLOCKING')
      return false;
  }
});
```

When navigating from `/users/1` to `/users` it should prevent navigation, but it fires the event handler in `listen`.  
The console log is:  

```
BLOCKING
The current URL is /users/1
The last navigation action was PUSH
```

When using `react-router-redux` it dispatches extra `@@router/LOCATION_CHANGE`.  
I am trying to migrate react-router v2 to v5 (history v2 to v5), but this issue didn't occur in the previous version.
Is it possible to prevent extra events when blocking it? I couldn't find anything in docs.

**Comment by goffioul** [comment]
I have a similar problem. I install a history listener to trigger a given action on URL change (in my case, I'm auditing URL changes). The app contains some components that may block back navigation, but even then, the history listener is still triggered. I might be able to work around the problem at the application level, but it doesn't seem natural that the history listeners are triggered when the navigation is cancelled. Is this intended behavior? If yes, what's the use case?

**Comment by BetterCallSky** [comment]
@mjackson
I reported it 1 year ago. Any chance to fix it?

**Comment by mjackson** [comment]
It's impossible to tell what could be going wrong without more information. Can you provide a reproducible test case I can look at?

**Comment by BetterCallSky** [comment]
@mjackson 
source code https://codesandbox.io/s/4qmn7l1260
video https://take.ms/h9BcL
blocking works fine if you call in code `history.push`, but it doesn't work correctly on the back button in the browser

**Comment by mjackson** [comment]
If you'd like to submit a PR that prevents the callback from being fired with the same URL, I'd be happy to merge. It's not a problem for React Router because the same pathname is a no-op.
