### ISSUE TITLE
Cannot include URL query in basename

### ISSUE THREAD

**Issue by goffioul** [ReactTraining/history#564]
I have a use case where my react app can be accessed using a URL that contains query parameters, e.g. `http://example.com/index.html?foo`. I create the history with `createBrowserHistory({basename:'/index.html?foo'})`. This produces warnings and I believe the path matching will not work. The root cause of the problem is that `PathUtils.hasBasename` does not escape special characters in `prefix` to create its regular expression.

**Comment by mjackson** [comment]
The basename does not support query parameters. It's a segment of the pathname.
