### ISSUE TITLE
Allow processing locations before passing to browser

### ISSUE THREAD

**Issue by wmertens** [ReactTraining/history#565]
Proposal: add a `transformLocation` to the history options, and call it on all locations that are provided by the application; use the resulting location object (ignore falsy result)

```js
// example
createBrowserHistory({
  transformLocation: loc => loc.pathName.startsWith('/xx/') && {
    ...loc,
    pathName: `/${currentLang}/${loc.pathName.slice(4)}`,
  },
})
```

Use case: In my application, the language is the first part of the URL. Most of the time when making links, they have to be "absolute", but the current language is not known in the part of the application that makes the link.

Right now I need to use `LangLink` which wraps `Link` and grabs the language, and replaces a leading `/xx/` with the language, but that doesn't work for e.g. `history.push()`

**Comment by goffioul** [comment]
Can't you use `basename` option when creating the history object, and then use method `createHref` to create valid link URLs?

**Comment by wmertens** [comment]
* `basename`: no, because it changes during the application lifetime
* `createHref`: I would like to avoid any wrapping of Links or history methods, as well as any extra work on the API user side…

**Comment by mjackson** [comment]
It feels like the right place to handle this kind of thing is in React, e.g. with your `<LangLink>` component. React provides a composition model, but the history library doesn't.

Why are you concerned about someone calling `history.push` directly? Why don't you just do all navigation with your `<LangLink>`s?
