### ISSUE TITLE
Reset/clear history

### ISSUE THREAD

**Issue by abdulrahman-khankan** [ReactTraining/history#567]
Not really an issue, but more of a question that I didn't find answer to in the documentation. (or possibly a feature request)

Is there a way to reset the history?

I have the following scenario/use case:
Sometimes the user might reach a form directly (via URL), and in normal cases, the cancel button triggers a goBack(), but when they go there directly, the previous page might not be part of the app (even an empty tab, as an empty tab is considered a page) they will go back to that page instead and leave the app. But, if they request the form normally (reachable from more than one place), the cancel button works great and they go back to where they were.

I thought about checking for the history.length, and if it's less than 2 then just go to a specific route instead of the goBack().
However, that wouldn't work unless I manage to reset the history. How can I do that? Is it something this package can do (now or in the future) or it is something on browser level and cannot be accessed?

Thanks!

**Comment by abdulrahman-khankan** [comment]
From MDN: 

> There is no way to clear the session history or to disable the back/forward navigation from unprivileged code. The closest available solution is the location.replace() method, which replaces the current item of the session history with the provided URL.

So probably cannot be done. If you confirm this, the issue is ready to be closed.

---
For others having similar scenarios:
I managed to workaround it by adding a boolean state after the history is imported and then check before going back if that boolean is set or not.

main.js
``` main.js
import { createBrowserHistory } from "history";
browserHistory = createBrowserHistory();
browserHistory.replace({ firstPage: true });
```

util.js
``` util.js
/**
 * Go back or redirect to URL
 * @param {{location: {firstPage: boolean}}} history History object.
 * @param {string} fallbackURL URL to redirect to if it is the first page.
 */
const goBack = (history, fallbackURL) => {
  if (!history.location.firstPage) {
    history.goBack();
  } else {
    history.push(fallbackURL);
  }
};
```

component_reachable_directly_by_URL.js
``` component_reachable_directly_by_URL.js
import { goBack } from "../util";

...

cancel() {
  goBack(this.props.history, "/route_to_redirect_to");
}
```

**Comment by mjackson** [comment]
There's no way for us to programmatically reset the history stack (at least in a browser, in memory history this would be trivial). If you need to clear the history stack for some reason, I'd suggest you use `window.location.reload()`.
