### ISSUE TITLE
history.push without notifying subscribers

### ISSUE THREAD

**Issue by donysukardi** [ReactTraining/history#572]
Is it currently possible to call history.push without notifying subscribers, i.e. just calling browser's `history.pushState` API internally to replace the URL?

**Comment by pshrmn** [comment]
No, it is not possible within the `history` package and I don't see this being added because it could lead to inconsistent states in your application. As you mentioned, you could just call `history.pushState` yourself if you really want this functionality, but I wouldn't recommend it.
