### ISSUE TITLE
when history action is different to 'POP' ?

### ISSUE THREAD

**Issue by marcosguti** [ReactTraining/history#575]
I'm trying to differentiate two paths to get to the same route, example with  react-router-dom it was differentiating the action PUSH or POP, but here I see that it is always POP, how i can obtain a different  action?

**Comment by pshrmn** [comment]
The action is `PUSH` when you call `history.push`, `REPLACE` when you call `history.replace`, and `POP` on initial load, when you call `history.(go|goBack|goForward)`, and when you navigate using the browser's forward/back buttons.

**Comment by marcosguti** [comment]
thanks
