### ISSUE TITLE
Replace isn't working as expected.

### ISSUE THREAD

**Issue by FahdW** [ReactTraining/history#580]
I have a login page and when the user logs in i have a replace to push them to a landing page. However the user is still able to press back and go back to the page they were at. Shouldn't replace remove that initial page.

**Comment by pshrmn** [comment]
It is difficult to say what the issue is without seeing your code, but this is most likely an issue on your end.

**Comment by FahdW** [comment]
I was using store.dispatch(replace()) from react-router-redux and it doesn't seem to be changing the stack

**Comment by pshrmn** [comment]
If you can put together a reproducible example demonstrating a bug, we can open this back up, but from what I can tell, the issue you are experiencing is not being caused by `history`.
