### ISSUE TITLE
history.length - The number of entries in the history stack is higher than one even on first page load

### ISSUE THREAD

**Issue by timotgl** [ReactTraining/history#582]
I'm using `react-router-redux` and logging all actions of type `@@router/LOCATION_CHANGE`. On the first page load `history.length` already has a value of `10` for some reason. I'd expect `history.listen` to be called many times, but it gets only called once. Is this expected? I'm trying to find a reliable way to determine wether the app is still at its initial, server-side page load or client-side navigation has happened already.

**Comment by pshrmn** [comment]
If you navigate to the site in a tab where you have been visiting other pages, `history.length` will be >1. `history.length` is the number of locations in the joint session history, not the current site's session history. This value also maxes out at 50. In general, I wouldn't recommend relying on `history.length` for anything.

One way to distinguish the initial location is that it won't have a `key` (I wish it did, but it doesn't). I'm not sure why you want to track the initial location, but there are some usage patterns you'll have to keep in mind: 1) the user is using forward/back buttons and refreshing the page and 2) manually entering the URI in the address bar in the middle of a session. Those might mess with the concept of what the initial page is.

**Comment by mjackson** [comment]
Thanks for the comment, @pshrmn. You're right on.
