### ISSUE TITLE
history.push/replace keep appends in the url

### ISSUE THREAD

**Issue by daeanza** [ReactTraining/history#586]
i create some tab (animal and fruit) with history.push function on each with dynamic parameter
`changeConditionTab(tab){
 history.push({
  pathname: 'baseUrl/${id}?tab=${tab}',
 });
}`
with the code above, when the tab get clicked the url change into `baseUrl/2?tab=animal`, but when the other get clicked the url appending into `baseUrl/2?tab=animal?tab=fruit` and keep appending if i try to click the tab `baseUrl/2?tab=animal?tab=fruit?tab=fruit....`

**Comment by mjackson** [comment]
You need to use a `/` at the beginning of your URL, otherwise it's a relative URL and will keep appending to the current URL.
