### ISSUE TITLE
SessionStorage throws an error on Mobile Safari 10.0

### ISSUE THREAD

**Issue by RaulTsc** [ReactTraining/history#587]
Hi guys,

We are running `"history": "3.0.0",` and we are seeing an error on Mobile iOS 10.3.3 - Safari 10.0.

It throws the error "The operation is insecure" when trying to access window.sessionStorage if cookies are disabled.

[Click me](https://imgur.com/a/fau652z)

Is this expected behaviour?

We're also thinking of a fallback for when users disable cookies -- there's really not much they can do in our app without cookies :).

**Comment by mjackson** [comment]
We ditched session storage in 4.0 because of this limitation. We now only use `pushState` storage, which works even when cookies are disabled. Please upgrade!
