### ISSUE TITLE
question about the bundle result/size

### ISSUE THREAD

**Issue by lili21** [ReactTraining/history#588]
![image](https://user-images.githubusercontent.com/4456380/39517062-57166f32-4e31-11e8-9e0b-c15d80be6f41.png)

```javascript
// source code
import createBrowserHistory from 'history/createBrowserHistory';

export default createBrowserHistory();
```

I'm only using `createBrowserHistory`.

**Comment by mjackson** [comment]
`history/createBrowserHistory` does not require `createHashHistory` or `createMemoryHistory`, so I'm not sure why these other files seem to be showing up in your bundle. But in order for us to help you we need to know the version you're using and something about how you're doing your build.

**Comment by lili21** [comment]
looks like `react-router` require it.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/index.js

is there any way to remove it ?
