### ISSUE TITLE
Document that basename should only be a relative URL

### ISSUE THREAD

**Issue by waynebloss** [ReactTraining/history#590]
Since there is no standard definition for what a basename is within the browser environment, I wasn't sure if I could pass an absolute URL or only a relative URL as the basename option. There is a [base href](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base#Attributes) which can be an absolute or relative url. There is also the [Unix basename](https://en.wikipedia.org/wiki/Basename), which has output very similar to a relative url.

I wanted to find an answer without digging through the code if possible. [This comment](https://github.com/ReactTraining/history/issues/404#issuecomment-271393817) about prefixing basenames with  `/` finally confirmed to me that basename should probably only be a relative URL.

Of course the examples you show only use relative URLs, but I wanted to be sure.

So, I think you should point that out in the documentation. If you want a pull request for that I'll be glad to do it, the change should only be a few bytes.

Thanks!

**Comment by waynebloss** [comment]
Ahh, ok thank you. I wasn't looking at the react-router docs because I'm not using react-router, just the history package. So, I was only looking at the README here - https://github.com/ReactTraining/history#using-a-base-url

I guess most users are just using react-router so I'll just close this now. Thanks again!

**Comment by waynebloss** [comment]
Also, the readme itself does kinda say it - 'If all the URLs in your app are **relative** to some other "base" URL, '  LMAO

**Comment by pshrmn** [comment]
Sorry, I didn't actually realize this was the `history` repo when I made that comment. I get notifications for both, with RR ones being more frequent, so I wasn't paying close attention. A PR here would be welcome, too!
