### ISSUE TITLE
Use babel-runtime to avoid inlining helpers

### ISSUE THREAD

**Issue by NeoLegends** [ReactTraining/history#592]
Hey!

I noticed that in the build output all the required babel helpers are inlined. This adds bloat to application bundles, so what about using `babel-plugin-transform-runtime` and depending on `babel-runtime` to get rid of these? :)

**Comment by pshrmn** [comment]
PRs are appreciated 😄.

**Comment by NeoLegends** [comment]
Done. Please see #593. :)
