### ISSUE TITLE
if path is absolute url, it would still prepend a leading slash to make it relative

### ISSUE THREAD

**Issue by stevemao** [ReactTraining/history#598]
```js
<Link to="https://example.com" />
```

expected:
```js
<a href="https://example.com" />
```

actual:
```js
<a href="/https://example.com" />
```

https://github.com/ReactTraining/history/blob/9ff690785f02d5c2554b860ff1a39a6527d18aa1/modules/LocationUtils.js#L55-L60

should check if the url is absolute instead of just a leading `"/"`

**Comment by pshrmn** [comment]
`history` only works for navigating within an application. If a path is absolute (begins with a `/`), it treats it as it, but if it is relative it will resolve the path using the current location.

If you need to navigate to a page outside of your single-page application, you should use a regular HTML anchor.

**Comment by stevemao** [comment]
> If you need to navigate to a page outside of your single-page application, you should use a regular HTML anchor.

That wasn't the case before. I'm pretty sure this changed without a major version bump.

**Comment by pshrmn** [comment]
Looking at the [blame](https://github.com/ReactTraining/history/blame/5f9ae0dd47f6297b6d42c195a9af07ecf5672825/modules/LocationUtils.js), early versions of `history` v4 only allowed absolute paths and relative paths were added in `v4.3` (while RRv4 was in alpha).

Whether or not it worked before (maybe in v3?), and despite the fact that you _can_ use the History API to navigate to other domains, I don't think that this package has ever intended to be used for external navigation.

**Comment by stevemao** [comment]
Thanks for the explanation. I do agree your point. In fact initially I used `<a />` to achieve this but thought would be handy to use `<Link />`. And I did a brief search and found out that react-router supported this (in an issue). Perhaps better documentation on this would be helpful?

**Comment by pshrmn** [comment]
Documentation improvement PRs are always appreciated,

Can you link the issue that recommended using absolute URLs with the `<Link>`?

**Comment by stevemao** [comment]
I must have remembered wrong sorry. All I found is https://github.com/ReactTraining/react-router/issues/1147#issuecomment-113180174 and I should've seen this before opening this issue. Sorry!
