### ISSUE TITLE
how to clear the history on logout (React Native)?

### ISSUE THREAD

**Issue by Mohamed3on** [ReactTraining/history#599]
So on RN, I basically want to say `history.clearAndPush('/login')` when the user logs out, so that we only have `'/login'` in the history object and the user can't go back to the logged in routes. Is there a way to clear the history array?

**Comment by pshrmn** [comment]
With RN, you are using the memory history, which stores the locations in an `entries` array (as well as an `index` value for storing the current location's index in the `entries` array). There isn't an API for resetting the history, but you can manually set these values.

```js
history.entries = [];
// history.push() auto increments from the current index
history.index = -1;
history.push("/login");
```

You might need to tweak that code slightly, but I think that that is all you need to do.

**Comment by Mohamed3on** [comment]
I suppose using `<ProtectedRoute>` as in https://reacttraining.com/react-router/native/example/auth-workflow would be the cleaner approach, if more time-consuming. Thank you though!
