### ISSUE TITLE
Ignore errors when saving hash history state if  `window.sessionStorage` is undefined in release 1.17.X

### ISSUE THREAD

**Issue by hseghetti** [ReactTraining/history#600]
I am using history release 1.17.0 and we must support some users which have disabled the storage in IE11. This issue was fixed in the history release 3.0.0. 

[https://github.com/ReactTraining/history/issues/295](url)

[https://github.com/ReactTraining/history/commit/3492e6c5350b4a1977aeabe9a11c2660bb0923d9#diff-405f4be94b4461d2c6e3f7726ae4698f](url)

I can not update the library version right now because I have a lot of dependencies. I am planning to start the library update asap but for now I want to insert the same fix present in the version 3.0.0 has part of the 1.17.X.

**Comment by pshrmn** [comment]
`1.17` is a 2.5 year old release and is no longer maintained. Your best bet would be to fork and make the changes yourself.

**Comment by hseghetti** [comment]
you are right. I was analyzing that option because 1.17 is no longer maintained. 
But I prefer to spent some times updating all the libraries. 

Thanks anyway, I will close the issue.
