### ISSUE TITLE
Please update `warning` package to "^4.0.1"

### ISSUE THREAD

**Issue by sidoruk-sv** [ReactTraining/history#601]
Got duplicated packages in my project instead (for now "history" depends on {"warning": "^3.0.0"})

**Comment by billyjanitsch** [comment]
This was already done in 2039fb322263e9517fbeac77d0e4d7b7f00d6bae. Wait for the next release :)

**Comment by amithgeorge** [comment]
Bump. Any timelines on a new release. Master seems to be ahead of the last released version by quite a bit now.
