### ISSUE TITLE
[Question] why is initial page load a POP

### ISSUE THREAD

**Issue by franciscolourenco** [ReactTraining/history#610]
This is a follow up question to the answer already given in: https://github.com/ReactTraining/history/issues/96

When a user opens a page for the first time, this page is added to the history, it doesn't exist yet. Event though history gets initialised on an existing URL, from the point of view of history, wouldn't it make sense that the initial action should be a "PUSH"?

**Comment by franciscolourenco** [comment]
bump

**Comment by mjackson** [comment]
Because you didn't do a push or a replace to get there. The `action` describes how you got there.
