### ISSUE TITLE
Static history

### ISSUE THREAD

**Issue by heygrady** [ReactTraining/history#612]
React router includes a `<StaticRouter />` component which is useful in server-side-rendering scenarios. There are cases where it's useful to have access to the static history object outside of the static router. For instance, preloading the data for routes in an SSR app.

My data loading functions mostly populate my redux store but sometimes they need to redirect. After initial server load, my app does client-side routing. This means I need my data preload to work on the server _and_ the client.

I would like to have those data loading functions operate the _exactly the same_ same on the client and the server. Following the [example in the react router manual](https://reacttraining.com/react-router/web/guides/server-rendering/data-loading), preloading data on the server is done before rendering; which means my preloading functions won't have access to the static history provided by `<StaticRouter />`.

To solve this issue, I extracted the static history from `<StaticRouter />` and made that available to my preload functions. Now they are able to call `history.push` as needed. This is tracked in `context` (like it would be with `<StaticRouter />`) and I can call a server redirect if necessary (after preload, before render). I check `context` again _after_ the render step to ensure that a redirect wasn't initialized during there.

I think `createStaticHistory` would be useful to add to the history project. As a separate issue, `<StaticRouter />` should allow `history` to be passed in from the outside.

This is the file I ended up with for `createStaticHistory`:

```js
// This code was unwrapped from  <StaticRouter />
// https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/StaticRouter.js

import invariant from 'invariant'
import { createLocation, createPath } from 'history'

const addLeadingSlash = (path) => {
  return path.charAt(0) === '/' ? path : `/${path}`
}

const addBasename = (basename, location) => {
  if (!basename) return location

  return {
    ...location,
    pathname: addLeadingSlash(basename) + location.pathname,
  }
}

const stripBasename = (basename, location) => {
  if (!basename) return location

  const base = addLeadingSlash(basename)

  if (location.pathname.indexOf(base) !== 0) return location

  return {
    ...location,
    pathname: location.pathname.substr(base.length),
  }
}

const createURL = (location) =>
  typeof location === 'string' ? location : createPath(location)

const staticHandler = methodName => () => {
  invariant(false, 'You cannot %s with <StaticRouter>', methodName)
}

const noop = () => {}

const createHref = (context, basename) => (path) => addLeadingSlash(basename + createURL(path))

const handlePush = (context, basename) => (location, state, status) => {
  context.action = 'PUSH'
  context.location = addBasename(basename, createLocation(location))
  context.url = createURL(context.location)
  if (status) {
    context.status = status
  }
}

const handleReplace = (context, basename) => (location, state, status) => {
  context.action = 'REPLACE'
  context.location = addBasename(basename, createLocation(location))
  context.url = createURL(context.location)
  if (status) {
    context.status = status
  }
}

const handleListen = () => noop

const handleBlock = () => noop

const createStaticHistory = (location = '/', context = {}, basename = '') => {
  const history = {
    createHref: createHref(context, basename),
    action: 'POP',
    location: stripBasename(basename, createLocation(location)),
    push: handlePush(context, basename),
    replace: handleReplace(context, basename),
    go: staticHandler('go'),
    goBack: staticHandler('goBack'),
    goForward: staticHandler('goForward'),
    listen: handleListen,
    block: handleBlock,
  }

  return history
}

export default createStaticHistory

```

**Comment by mjackson** [comment]
This is outside the scope of this library.
