### ISSUE TITLE
Mutating history

### ISSUE THREAD

**Issue by pronebird** [ReactTraining/history#613]
Hi,

I have a scenario where a user can be on `/login` screen but at the same time can navigate into `/about` box. The user can log in from any screen. Now when log in happens I'd like to mutate history and replace all mentions of `/login` with `/home` to make sure that user does not end up on login after going back in history.

Since I use memory history I realize that I can access `entries` directly and just run over them and replace them as I please, i.e:

```
for (const entry of history.entries) {
  if (entry.pathname === '/login') {
    entry.pathname = '/home';
  }
}
```

This works fine, however I see that location objects use `key` and I think I use it somewhere else in react-router and I am not sure this is not going to break one day.

What's the recommended way of mutating the history or should I instead roll out my own implementation for such scenarios?

**Comment by gustavopch** [comment]
You don't need that.

Simply redirect to the home page whenever a signed in user tries to enter the '/login' route.

**Comment by pronebird** [comment]
@gustavopch I don't have "enter" events. But I have higher level events that tell me that user logged in and the currently displayed screen has to remain the same and the previous screen if it was "/login" has to be "/home"
