### ISSUE TITLE
[Safari] - history goBack not working as expected

### ISSUE THREAD

**Issue by Ben07** [ReactTraining/history#615]
`
history version:  4.7.2
macOS version: 10.13.6
Safari version:    11.1.2 
`
When navigating to a page via <Link to="/foo"> and then using history.goBack(), app remains
on the same page. Only until 2 or more invocations of history.goBack() via some interaction (button) does the page actually go back.

Worth noting also, replacing goBack with go(-1) does not solve the problem either.

This has been isolated to Safari only. Not able to reproduce on Chrome or Firefox.

Using the Safari browser back button gives the exact same behaviour.

**Comment by zsajjad** [comment]
Any update on this?

**Comment by zsajjad** [comment]
I feel there is some issue with the state in `window.history`. I checked `window.history` object on every click of my back button, it appears as when there is `key` in state object it `window.history.go(-1)` works as desired else it just stays on the same page.
