### ISSUE TITLE
Is there a way to prepend listeners?

### ISSUE THREAD

**Issue by matthew-dean** [ReactTraining/history#616]
I have a situation where I need to handle which component is focused first based on the state in the route. So I did this by adding a history listener. However, what I'm finding is that all the components for a route are rendered and mounted for a route BEFORE I ever receive a notification that a route has changed, which seems counter-intuitive. So I think what's happening is that all of `react-router` is listening to route changes and re-rendering (and mounting), since those listeners were added first.

Is there a way to specify that a listener should be at the top of the stack? Or some other event to listen to before it would call other listeners?

**Comment by pshrmn** [comment]
@matthew-dean where are you adding your listener? If you create your own `history` instance and register your listener before mounting your `<Router>`, that listener would be called first. It is hard to say if that would help without seeing exactly what you're trying to do, but that is the closest thing you can do to prepending.
