### ISSUE TITLE
Passing objects as state in history.push

### ISSUE THREAD

**Issue by AllanPamplona** [ReactTraining/history#621]
React version: 16.4.1
React router: 4.3.1

I'm trying to pass an object to another component through history.push method but it doesn't work.
There's no errors, just doesn't work.

When i change the state object for a string it works.
My code:
```
this.props.history.push('/template', { detail: user})
```
where user is an object.

When i try: 
```
this.props.history.push('/template', { detail: 'something'})
```
It works.

Is this a bug? or expected behavior?

**Comment by pshrmn** [comment]
`state` must be serializable (see the [`pushState()` documentation](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method)).

You might be able to use `JSON.stringify()` and `JSON.parse()` for storing the object. However, I generally recommend against using `state` to store anything but ephemeral data (like a URL to redirect to after logging in). In addition to the serializable requirement, `state` also does not exist on direct navigation.

If you want to persist some data across pages, you can probably keep a cache (which could be as simple as an object) in your application that you write to before pushing and read from in your `/template` component.

```js
const cache = {}
// navigating to detail
cache["user"] = user;
history.push("/template");

// rendering /template
const user = cache["user"] // also handle an empty cache?
```
