### ISSUE TITLE
How to get previous location when using history.listen?

### ISSUE THREAD

**Issue by dreamerblue** [ReactTraining/history#626]
React router v4.2.0

When using history.listen like this:

```js
history.listen((location, action) => {
    ...
})
```

I wanna get the previous location when history changing. Thus I can determine whether I should do something (e.g. exec some function only when pathname === prevPathname and query !== prevQuery).

So is there any method to get previous location when using history.listen?

**Comment by mjackson** [comment]
The best you can do is something like this:

```js
let prevLocation;

history.listen(nextLocation => {
  console.log(prevLocation);
  // ...
  prevLocation = nextLocation;
});
```
