### ISSUE TITLE
createbrowserhistory not honourning getUserConfirmation setting ?

### ISSUE THREAD

**Issue by garyng2000** [ReactTraining/history#627]
It seems that it has been overwritten in the code to use the builti-in getConfirmation regardless what is supplied. This seems to be the case only for createbrowserhistory, not sure why. please change documentation of there is a good reason

**Comment by pshrmn** [comment]
The described behavior should not happen; the default user confirmation function is only used [when no function is provided](https://github.com/ReactTraining/history/blob/05e541e24a73e5fbeaa6a88f0fa1839031d8e35e/modules/createBrowserHistory.js#L46). Please provide code demonstrating the issue.

**Comment by garyng2000** [comment]
below is the code I use, may be I used it in a wrong way. But if I create the history object first then pass it to the router, this function is not honoured. if I put it in the router constructor directly(as shown), it behaves as it should be. so may be it is the react-router that I misunderstood.

const hist = createBrowserHistory(
  {basename:process.env.NODE_ENV === "development" ? appProxyBasename : appBasename, getUserConfirmation:getUserConfirmation }
);

const baseName = process.env.NODE_ENV === "development" ? appProxyBasename : appBasename;

render(
  <Provider store={store}>
    <Router basename={baseName} hist={hist} getUserConfirmation={getUserConfirmation}>
      <ScrollToTop>
        <App/>
      </ScrollToTop>
    </Router>
  </Provider>,
  document.getElementById('root')
);

**Comment by garyng2000** [comment]
may be it is the react-router that I mistunderstood. I have to pass it from there as a property rather than as part of the history object(where I wanted to attach the function) which goes to the router constructor.

**Comment by pshrmn** [comment]
Unless you are using the base `Router` (`import { Router } from "react-router-dom"`), a `history` object will be created for you. If you attempt to pass your own `history` object to a `BrowserRouter`, you should get [this warning](https://github.com/ReactTraining/react-router/blob/2079f46773a3cf78857a7e31469c2d8a3766fae4/packages/react-router-dom/modules/BrowserRouter.js#L29-L33).
