### ISSUE TITLE
Breaking changes?

### ISSUE THREAD

**Issue by brandondurham** [ReactTraining/history#629]
Are there breaking changes listed anywhere for major version releases?

**Comment by TrySound** [comment]
Changelog?
https://github.com/ReactTraining/history/blob/master/CHANGES.md

**Comment by mjackson** [comment]
We currently keep things in the CHANGES.md file, but I'm planning on having more detailed release notes going forward on each release page (i.e. [like this](https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.1)).

**Comment by brandondurham** [comment]
What’s the opposite of a “wild goose chase?” A “tame duck?”

I have CHANGELOG so burned into my brain that I didn’t see the next best thing: CHANGES. I do love release notes, though. Either way, thanks for the help!
