### ISSUE TITLE
How to forceRefresh only for a particular route ?

### ISSUE THREAD

**Issue by arun-xandr** [ReactTraining/history#630]
Currently the forceRefresh prop is at the global level of BrowserRouter component. I have a requirement to force refresh only for a particular history.push (navigating away to a different context root). Is there any existing way to achieve this ?

**Comment by chrisPfaff** [comment]
when you say "force refresh" do you just want to re-render?

**Comment by arun-xandr** [comment]
@chrisPfaff no, I wanted to do full browser reload. basically  `window.location.href = href;`

**Comment by drewandrew** [comment]
I've been using this for now
``` js
history.push(...);
window.location.reload(true);
```
