### ISSUE TITLE
Special instructions for tree-shaking?

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/history#635]
What special steps do people need to take in order to get the smallest bundle? We used to recommend that people `import createBrowserHistory from "history/createBrowserHistory"`, but that is going to be deprecated in the next minor release. I just want to make sure we have a clear set of guidelines for people who are upgrading and want to take advantage of tree-shaking.

/cc @TrySound

**Comment by TrySound** [comment]
Just use webpack production mode or rollup with replace and uglify/terser plugins.
https://github.com/ReactTraining/history/blob/master/.size-snapshot.json#L7-L13

**Comment by TrySound** [comment]
rollup-plugin-replace is the same as `DefinePlugin` in webpack

**Comment by mjackson** [comment]
Thanks. I'll add a section to the README about this.
