### ISSUE TITLE
history lost when IOS PWA is closed - history not persistant

### ISSUE THREAD

**Issue by zsolt-dev** [ReactTraining/history#645]
Hello,

when you add your offline capable app on the home screen on IOS, history is not preserved. It works fine on android. 

WHAT HAPPENS:

1. Open PWA from homescreen icon
2. Opens to default opening page
3. Navigate to specific page within PWA
4. Return to homescreen
5. Open PWA from homescreen icon
6. Opens to default opening page

WHAT I'D LIKE TO HAPPEN:

1. Open PWA from homescreen icon
2. Opens to default opening page
3. Navigate to specific page within PWA
4. Return to homescreen
5. Open PWA from homescreen icon
6. Opens to navigated page from above in #3

question 1) What would be a good workaround? Is there a way to restore the history from localstorage or some other storage that will persist?

question 2) is it a "bug" in safari that is going to fixed? Should we just wait, instead of fixing it in the router?

thank you

**Comment by dreadcast** [comment]
Hi,

Which method are you using ? Memory, Browser or Hash ?

**Comment by zsolt-dev** [comment]
Hi,

package.json
```json
    "react-router-dom": "^4.3.1",
```

index.js
```js
import { BrowserRouter } from 'react-router-dom';
        <BrowserRouter>
          <App  />
        </BrowserRouter>
```

**Comment by dreadcast** [comment]
I'm not sure wether this is a _bug_ or not in  Safari, but you could of course use `localStorage` in order to store latest route. Then when relaunching app, redirect to this _latest route_
