### ISSUE TITLE
Document base href referring to other host breaks history.push/replace

### ISSUE THREAD

**Issue by mklopets** [ReactTraining/history#648]
An app situated at `foo.com` has a `<base href="bar.com">` tag in its HTML because that's where all of its assets (e.g JS bundle and images referred to in CSS) are served from.

`history.push` can't be used in this app because, similarly to `window.history.pushState`, the relative path it takes is interpreted with respect to the document's base href. This means that `history.push({ ...currentLocation, query: 'a=b' })` essentially executes `window.history.pushState({}, '', '?a=b')` which, since the browser itself respects the base href on such native method calls, means trying to push `bar.com?a=b` to the history. This fails due to cross-origin history manipulation not being allowed.

The native `pushState` method allows this problem to be bypassed by specifying the correct absolute URL: `window.history.pushState({}, '', 'http://foo.com?a=b')`. This library, however, only seems to allow specifying the pathname part of the URL.

I'm also using react-router, so using the native browser method (although it technically works) means (as far as I understand) that there's no way to make the app realise that it is now open at a different path after the history push.

Not really sure if this is a bug report or a feature request. I see two potential changes to the library that could solve my problem:
1) history.push/replace optionally takes in the `host` part of the location too or it takes in the full URL to push
2) history.push/replace overrides default browser behaviour of fully respecting the base href by prefixing the pushed location with the current `window.location.origin`. I don't think this would break anything, because nothing should effectively change for those using base hrefs on the same host.

If one of these approaches is acceptable, I could try and open a PR.

**Comment by mjackson** [comment]
Since this is a client-side history library, it should be self-evident that it doesn't work across separate domains. But if you'd like to add a note to the docs to make it even more obvious please feel free to submit a PR.

**Comment by mklopets** [comment]
@mjackson You might have misunderstood the issue – I do want to remain on the single domain as a result of the push/replace, just the base href is on another due to assets coming from elsewhere.
