### ISSUE TITLE
[Safari (iOS)] - history.block does prevent the browser to go back

### ISSUE THREAD

**Issue by freeboarder42** [ReactTraining/history#669]
**Current behavior?**

When using `history.block` in a component, the browser's back button does not work in Safari on iOS (12) if the previous route was a route within the app. After tapping the back button, even (react-router) links do not work anymore.

**Test Case**

https://github.com/freeboarder42/react-safari-history-block-bug-demo

**Steps to reproduce**

* Create a simple React app with two components besides App.jsx (Home.jsx, ComponentWithHistoryBlock.jsx)
* Create routings to `Home` and `ComponentWithHistoryBlock` in App.jsx
* Place a link to `ComponentWithHistoryBlock` on `Home`
* Place a link to `Home` on `ComponentWithHistoryBlock`
* Add following code in  `ComponentWithHistoryBlock`:

```
constructor(props) {
   super(props);

   const { history } = this.props;
   this.unblock = history.block('Really navigate away?');
}

componentWillUnmount() {
   this.unblock();
}
```
* Run the app in Safari on iOS (12)
* Use the link to `ComponentWithHistoryBlock` to go to `ComponentWithHistoryBlock`
* Tap the browser's back button
* Tap the `Home` link

**What is the expected behavior?**

The browser should go to the `Home` component when tapping the browser's back button. After this did not work, the browser should go to the `Home` component when tapping the Home link.

**Used Versions**

React: 6.8.2
React Router: 4.3.1 (just used for routing)
OS: iOS 12.1.4
Don't know if it worked in previous versions of React

**Comment by freeboarder42** [comment]
I just updated my [demo](https://github.com/freeboarder42/react-safari-history-block-bug-demo) to only use history, and not use react-router.

**Comment by freeboarder42** [comment]
According to some tests I did, the source of the issue is that Safari on iOS does not display the dialogs of window.confirm and window.alert while navigating backwards or forwards. window.confirm unfortunately directly returns false. This means that DOMUtils.getConfirmation thinks, the user has denied the navigation.

**Comment by pshrmn** [comment]
In that case, there isn't really anything that `history` can do about it. The best solution would be to use a custom `getUserConfirmation` function that uses something other than `window.confirm` (although I'm not sure what alternative should be used).

You could possibly also open a PR to update the README's section on [`getUserConfirmation`](https://github.com/ReactTraining/history#customizing-the-confirm-dialog) to note the problem.

**Comment by freeboarder42** [comment]
And just for developers facing the same problem: When you use a custom prompt like described in https://kamranicus.com/posts/2018-07-26-react-router-custom-transition-ui, the prompt and the navigation work as expected also on iOS.
