### ISSUE TITLE
Middle Mouse Button not working

### ISSUE THREAD

**Issue by kevinlucero** [ReactTraining/history#671]
Does middle button works?
it seems mouse middle button not working as expected, to open new tab.

**Comment by pshrmn** [comment]
This package doesn't affect middle mouse button clicks.

Your router should detect those and let the browser handle them natively. For example, React Router's [`Link`](https://github.com/ReactTraining/react-router/blob/e726e991259a941c51a08a82b9901d6aa1264144/packages/react-router-dom/modules/Link.js#L20) ignores non-left click events (i.e. let's the browser handle them instead).

**Comment by kevinlucero** [comment]
thanks for responding , i am just curious about that , but about you said, i will handle it manually thanks 👍 👍
