### ISSUE TITLE
Add something to tell if action was backward or forward in listen function

### ISSUE THREAD

**Issue by tholander** [ReactTraining/history#676]
I'm trying to make breadcrumbs for an app, and wanted to distinguish `goBack` and `goForward` by the value of `action` parameter. But any call to `go` function returns a `POP` action.
Is it possible to add something in the `listen` function to distinguish if whether it's a `goBack` or `goForward` ?

**Comment by mjackson** [comment]
The browser doesn't tell us whether the back or forward buttons were clicked, only that a `POP` happened. You can probably try doing something like saving some extra location state on each navigation with a counter, and then comparing the counter whenever you get a `POP`. But we don't have any plans to support something like that in core yet. It's definitely an interesting feature request though.
