### ISSUE TITLE
history/createBrowserHistory broken for TS on latest release (v4.9.0)

### ISSUE THREAD

**Issue by uorbe001** [ReactTraining/history#681]
We are using this module on TS, and we started getting runtime errors when v4.9.0 was released this weekend. The error we are getting is this one:

```TypeError: createMemoryHistory_1.default is not a function```

We also tried changing the imports to the new style (`import { createBrowserHistory } from "history";` but that doesn't help, we are still seeing the same error.

I tried looking at the code to try to find the mistake, but I can't find anything wrong, I suspect it is related to the babel upgrade, which must have broken the exports somehow. Any way I can help debug this? Thanks

**Comment by dkadrios** [comment]
I'm running into something similar which I assumed was an issue with Parcel, but perhaps it all is babel related.

With either style of importing I get
ENOENT: no such file or directory, open '<path>/node_modules/history/es/index.js'

**Comment by uorbe001** [comment]
@dkadrios the babel thing is just a theory with no data to back it up. Looking at the change history it seems it would likely be related to either babel or rollup. I'm gonna try to run a binary search later to see if I can find which commit introduced it to be a bit more helpful.

**Comment by uorbe001** [comment]
Ok, the broken change here was introduced between these tags https://github.com/ReactTraining/history/compare/v4.7.2...v4.8.0-beta.0 . A bisect tells me it was introduced on 094bcc73de5722c94b4063cc5a0ed54ac269e182. That seems to be because the node entry point was changed on this commit, but the actual broken change must have been introduced before that. I think the most likely culprit is 20f3959851851839bc20b9c2d926dea7746a1168 and the change to rollup.

**Comment by bogdan-calapod** [comment]
Is there any workaround until a fix is pushed ?

**Comment by wildcart** [comment]
This probably wont help the OP but it may help anyway: Version 4.9 works for us with TypeScript 2.8, at least the page loads normally and I haven't seen any regression so far. I did have to change the import statement to match the one posted by the OP (also mentioned in the documentation).  Upgrading from 4.7.2 to 4.9, otherwise, causes the above error.

However, I get the same warning as reported in #680 about using some deprecated 'import/require' statement but this doesn't seem to cause any problems.

**Comment by uorbe001** [comment]
>This probably wont help the OP but it may help anyway: Version 4.9 works for us with TypeScript 2.8, at least the page loads normally and I haven't seen any regression so far.

We are using TS v3.3.3333 (I love that version number), so downgrading TS because of this lib seems like shooting my own foot tbh. 

>Reverting to 4.7.2 (instead of ^4.7.2) in both our main package.json and changing the dependencies of react-router and react-router-dom in package-lock.json to force 4.7.2 fixes it, but obviously this is not ideal.

We've done this as a temporary fix, but I would like to solve it in a better way.

**Comment by mjackson** [comment]
We have tests for all our builds that consume the library directly, so I'm not sure what's happening here (see e.g. [this test](https://github.com/ReactTraining/history/blob/2d8bb51e2b43582cf631f4cd9ab080c43676af88/modules/__tests__/MemoryHistory-test.js#L1) which uses `import { createMemoryHistory } from 'history'` without any problems.

Can you provide us with a minimal repro?

**Comment by uorbe001** [comment]
Sorry for the late reply, totally forgot about this. I've created this [gist]( https://gist.github.com/uorbe001/e0df01a80d833f49a7a2a81a62dd3880), using that (on an empty directory, just `npm install` and `npm test`) it gives me this:

```
> blah@1.0.0 unit /Users/uorbe001/Projects/gamevy/history-replicate
> TS_NODE_CACHE=false npx mocha index.spec.ts --require ts-node/register

Warning: Please use `require("history").createMemoryHistory` instead of `require("history/createMemoryHistory")`. Support for the latter will be removed in the next major release.


  Balh
    1) has a default route


  0 passing (38ms)
  1 failing

  1) Balh
       has a default route:
     TypeError: createMemoryHistory_1.createHistory is not a function
      at Context.<anonymous> (index.spec.ts:6:19)


```

You can check on the history that I tried different imports, all with the same result.

**Comment by robinjoerke** [comment]
I had the same issue. When i changed the import form
`import createBrowserHistory from 'history/createBrowserHistory';`
to
`import {createBrowserHistory} from 'history';`
to resolve the deprecation warning the issue also disappeared. so is this issue somehow related to the warning?

**Comment by tomodian** [comment]
in my case, I was creating a file called `history.ts` and it was conflicting with `history` package.

In history.ts,

```
import { createBrowserHistory } from 'history' // --> seems like a conflict
export default createBrowserHistory()
```

so I renamed my file to `browserhistory.ts` and it worked fine again.

In browserhistory.ts,

```
import { createBrowserHistory } from 'history' // --> no more conflict occurs
export default createBrowserHistory()
```

hope it helps!

**Comment by mjackson** [comment]
Thanks for the workaround, @tomodian. Seems like a limitation of TS, so I'm going to close. If there's anything else we can do to better support you here, please let us know.
