### ISSUE TITLE
Some CJS exports are missing

### ISSUE THREAD

**Issue by jhiode** [ReactTraining/history#682]
Some deep-importable files are now stubs which are re-exports from `./index.js` but non of the exports are actually defined there.

So the the `index.js` looks like this:
```
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/history.min.js');
} else {
  module.exports = require('./cjs/history.js');
}
```
but `./cjs/history.js` for example has only these exports:
```
exports.createBrowserHistory = createBrowserHistory;
exports.createHashHistory = createHashHistory;
exports.createMemoryHistory = createMemoryHistory;
exports.createLocation = createLocation;
exports.locationsAreEqual = locationsAreEqual;
exports.parsePath = parsePath;
exports.createPath = createPath;
```

But where are all the stubbed exports (e.g. `DOMUtils`, `LocationUtils` etc)?

**Comment by pedrodias2703** [comment]
This might be causing this https://github.com/ReactTraining/react-router/issues/6645

**Comment by ZauberNerd** [comment]
@jhiode seems like this is intended:
- https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.1
- https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.2

**Comment by TrySound** [comment]
These utils are private and not intended to be reused in user code. Some of them are available though.
https://github.com/ReactTraining/history/blob/master/modules/index.js

**Comment by mjackson** [comment]
`DOMUtils` and `LocationUtils` are not part of our public API. The new single-file bundle hopefully makes that more obvious.

**Comment by jhiode** [comment]
Thanks for the clarification.

I don't need these imports but as you have actually [warnings for this scenario](https://github.com/ReactTraining/history/blob/master/warnAboutDeprecatedCJSRequire.js#L31)  I thought you would still consider it to be a bug 🙂
