### ISSUE TITLE
proper changelog

### ISSUE THREAD

**Issue by orangecoding** [ReactTraining/history#686]
Maybe it is just me, but on npm, there's now v 4.9.0. 
Changes.md shows 4.6.3 as latest version. Github releases page is spammed with beta releases... can we plz have a change log that is up to date and showing what xactly has changed?

**Comment by orangecoding** [comment]
honestly? You are closing this without even adding a comment to this? What the heck?

**Comment by vladshcherbin** [comment]
@orangecoding get used to it, it's his project and he does what he wants and doesn't care what people ask. Kinda makes sense as it's an OSS, but still unpleasant to experience knowing how maintainers of other packages handle same issues.

Unfortunately this package is used everywhere and this won't change in the near future. 🤷‍♂️

**Comment by orangecoding** [comment]
To me this is a middlefinger into the os community. But who am I to judge.
