### ISSUE TITLE
Last Visited Page

### ISSUE THREAD

**Issue by nenecmrf** [ReactTraining/history#691]
Hello, how can i get the last link i visited?

**Comment by razchiriac** [comment]
history.entries is an array.  So you could do history.entries.peek()

**Comment by mjackson** [comment]
@razchiriac That only works with `createMemoryHistory`, not with `createHashHistory` or `createBrowserHistory`.

@nenecmrf Browsers don't give us an API for finding the last URL you visited, but you can track it yourself:

```js
let lastLocation = null;

history.listen(location => {
  // ...
  lastLocation = location;
});
```
