### ISSUE TITLE
4.9.0 different in npm release than github tag

### ISSUE THREAD

**Issue by jkup** [ReactTraining/history#696]
Hey all!

We are using History through React Router and have a bug which is fixed by this commit https://github.com/ReactTraining/history/commit/78f016f6e5b49e2a23ec41799faf160dd68d6b6b

When I look on GitHub at the 4.9.0 tag I see that commit in the list of fixes https://github.com/ReactTraining/history/compare/v4.9.0...master

However when I check out, for example, the 4.9.0 UMD build I still see that removed code in there (https://unpkg.com/history@4.9.0/umd/history.js). Is there a mismatch between the GitHub tag and the npm release?

**Comment by jasonmosley** [comment]
Can one of the maintainers tag and deploy this fix to NPM please?

**Comment by oskarolsson-jimdo** [comment]
There seems to be some confusion here. The changes in https://github.com/ReactTraining/history/commit/78f016f6e5b49e2a23ec41799faf160dd68d6b6b were merged, but never released. It's supposed to be in a new major release (v.5) but that has not yet been released.

**Comment by jkup** [comment]
@oskarolsson-jimdo Why is it in the v4.9.0 tag? https://github.com/ReactTraining/history/compare/v4.9.0...master

**Comment by StringEpsilon** [comment]
@jkup "v.4.9.0 ... master" means: "All commits from the 4.9.0 tag to the current head of master". I.E. that selection includes all commits that were made **after** the release.

**Comment by jasonmosley** [comment]
But that package is broken for us until those commits are in. Well just have to fork it.

**Comment by jkup** [comment]
Ty all for the explanation!
