### ISSUE TITLE
Attempted import error: 'DOMUtils' is not exported from '../esm/history.js'.

### ISSUE THREAD

**Issue by xiaoyuaiheshui** [ReactTraining/history#697]
when I run "npm run build", it shows some errors:
here is the logs:
05:57:04 Creating an optimized production build...
05:58:55 EXITCODE   0Failed to compile.
05:58:55 
05:58:55 ./node_modules/history/es/DOMUtils.js
05:58:55 Attempted import error: 'DOMUtils' is not exported from '../esm/history.js'.
05:58:55 
05:58:55 
05:58:55 npm ERR! code ELIFECYCLE
05:58:55 npm ERR! errno 1
05:58:55 npm ERR! metro-construction-mi@1.0.0 build: `react-app-rewired build`
05:58:55 npm ERR! Exit status 1

**Comment by yudhir** [comment]
Revert to 4.7.2 version

**Comment by mjackson** [comment]
`npm run build` is working fine for me on master
