### ISSUE TITLE
A redirect throws a bad notifyListeners triggered

### ISSUE THREAD

**Issue by navarroaxel** [ReactTraining/history#703]
I found a bug trying to do a redirect from `react-redux`. Looks like the `notifyListeners` is not working properly and a `delay` (setTimeout) on the `push` is a good work around for this issue.

Bug demo repo: https://github.com/navarroaxel/react-history-redirect

```
node@10.15
npm@6.9.0
react@16.8.6
connected-react-router@6.4.0
react-router@5.0.0
```

**Comment by mjackson** [comment]
I'm sorry, but we don't support `connected-react-router` on this repo. You may have better success opening an issue with them.
