### ISSUE TITLE
react-router-docs/api 404

### ISSUE THREAD

**Issue by fosteman** [ReactTraining/history#705]
[<Link/> documentation](https://knowbody.github.io/react-router-docs/api/Link.html), when clicked on [Location Descriptor](https://github.com/mjackson/history/blob/master/docs/Glossary.md#locationdescriptor) redirects to a missing blob

**Comment by pshrmn** [comment]
There isn't a lot that we can do about that since it is third party documentation. There are branches for the old versions; you can see the file here:

https://github.com/ReactTraining/history/blob/v3/docs/Glossary.md#locationdescriptor

**Comment by fosteman** [comment]
Thanks @pshrmn , closing this issue then.
