### ISSUE TITLE
history.push("..") navigates too far up the path.

### ISSUE THREAD

**Issue by StringEpsilon** [ReactTraining/history#712]
I have a `react-router` project with some nested routes and want to programmatically navigate back up the tree / path. I tried to do this with `history.push("..")`.  But this navigates up by two segments, instead of one.

**Expected**:
Given the location `/foo/bar/baz`, I'd expect `push("..")` to navigate to `/foo/bar`

**Actual**:
Given the location `/foo/bar/baz`, executing `push("..")` results in the location `/foo/`

**Sandbox:** 
https://codesandbox.io/s/react-router-rsvuq 
(See the back buttons in /about and in /topics)

**Version(s)**:
history: 4.7.2 and 4.9.0.
react-router: 4.3.2 and 5.0.1

**Comment by StringEpsilon** [comment]
This is probably a bug in `resolve-pathname`. I'll let you decide whether or not to also track this here.

**Comment by pshrmn** [comment]
The final segment is not considered a directory because it does not have a trailing slash; if you were at `/foo/bar/baz/` and navigated to `..`, you would end up at `/foo/bar/`.

This isn't just `history`, you can get the same result in the browser using `history.pushState`.

```js
history.pushState(null, '', /test/ing')
// example.com/test/ing
history.pushState(null, '', '..');
// example.com
```

**Comment by StringEpsilon** [comment]
I see. I guess I expected URIs to behave more like unix paths. 

https://tools.ietf.org/html/rfc3986#section-5.2.4 

Nevermind then.
