### ISSUE TITLE
Bug in parsePath

### ISSUE THREAD

**Issue by natkuhn** [ReactTraining/history#714]
Currently the URL "/#foo?bar" is parsed to { pathname: "/", hash: "#foo?bar", search: "" }, not the desired { pathname: "/", hash: "#foo", search: "?bar" }.

Here is a codesandbox illustrating the problem: https://codesandbox.io/embed/failing-history-rnqzu
Add "#foo?bar" in the demo browser address bar and hit enter. Then look at the console output.

I [submitted a PR](https://github.com/ReactTraining/history/pull/713), sorry if it is overkill to also submit this as an issue, I don't completely know my way around.

**Comment by StringEpsilon** [comment]
https://tools.ietf.org/html/rfc3986#section-3 

The RFC specifies that:

The query part starts with a "?" and is followed by the fragment part ("hash"). 

> The query component is indicated by the first question
   mark ("?") character and terminated by a number sign ("#") character
   or by the end of the URI.
(Section 3.4)

> The characters slash ("/") and question mark ("?") are allowed to
   represent data within the fragment identifier. 
(Section 3.5)

The current behavior is correct.

**Comment by natkuhn** [comment]
OK, that is very surprising to me, but thank you for your time & explanation.
