### ISSUE TITLE
Why pop event triggered wrong while using createBrowserHistory()?

### ISSUE THREAD

**Issue by nt4f04uNd** [ReactTraining/history#715]
I'm listening for history
Why when I trigger `onpopstate` - which is event for back button on mobile platforms - POP event is triggered with same location as it is right now? Like if I'm on '/view' URL after pressing back button nothing changes. And this prevents me from using `window.onpopstate` because then it will cause ifinitely before it comes to first page in history.

```tsx
 history.listen((location, action) => {
         switch (action) {
            case 'POP':
               console.log(action, location)
               this.setState({ activeStory: location.pathname })
               return
            case 'PUSH':
               this.setState({ activeStory: location.pathname })
               return
            default:
               return
         }
      })
```

The result of triggering `onpopstate`
![image](https://user-images.githubusercontent.com/39104740/60399086-464f0a80-9b68-11e9-896d-168c94ca535a.png)

**Comment by pshrmn** [comment]
How are you triggering `onpopstate`?

**Comment by nt4f04uNd** [comment]
@pshrmn I'm not near my PC, I might be wrong. I was doing it like this
```js
window.disaptchEvent(new Event('popstate'))
```
And I bound this for my up arrow key like that
```js
window.onkeydown(e=>{
   if(e.keyCode==38){
    .....
  }
})
```
Btw, on mobiles all works fine, back event is listened with no problem by your package. I am working with vk-mini-apps template if you want to know. It's like a platform to build services inside social-network's (it's name is VK) native app using react. Your history module is a perfect way to build routing in it.

**Comment by pshrmn** [comment]
The `popstate` event doesn't actually change locations, it is only a notification that the location has changed. To change locations, you should use the (native) [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)'s `go` (or `back`/`forward`) methods. Those will change the location and then emit a `popstate` event (similar to the browser's back/forward buttons).
