### ISSUE TITLE
restore history.entries

### ISSUE THREAD

**Issue by crobinson42** [ReactTraining/history#717]
Is is possible to restore `history.entries` array with a previous history array. My use case is restoring an app (that was closed) with it's history maintained - ie: the user can open the app and click go back and expect to pop the last entry on `history.entries`.

What I've noticed is the path `key`'s are different on every re-load when using react-router and my naive solution **isn't working**:

```
// store history on every change
history.listen(() => {
  localStorage.set('navhistory', JSON.stringify(history.entries))
})

windowLoaded = () => {
 history.entries = JSON.parse( localStorage.get('navhistory') )
}
```

**Comment by pshrmn** [comment]
You can [pass an `initialEntries` array](https://github.com/ReactTraining/history/blob/763fc13bc8a52aff91d9594a7c1d944faa97961a/modules/createMemoryHistory.js#L17) when you create the `history` instance.

```js
history.listen(() => {
  localStorage.set('navhistory', JSON.stringify(history.entries))
});

// if `navhistory` doesn't exist, fallback to using the root location
const intialEntries = JSON.parse(localStorage.getItem('navhistory') ) || ['/'];
const history = createMemoryHistory({ initialEntries });
```
