### ISSUE TITLE
Lost of Session on Refresh (chrome macbook)

### ISSUE THREAD

**Issue by shavyg2** [ReactTraining/history#722]
So on safari when i click some links and then i go back and refresh, i still have the ability to use the back button. I can go back to previous pages, i have visited. I can't go forward after a refresh.

However on chrome when i do this, i can't go forward or back. 
Is this the correct behaviour? or is something wrong?

I am guessing under the hood it should be using window.history. which should give me those features.

I haven't tested any other OS yet.

**Comment by shavyg2** [comment]
i get true on both browsers for `window.history && 'pushState' in window.history`

**Comment by pshrmn** [comment]
Could you please provide a small demo application that demonstrates the behavior? I'm not quite understanding what you are describing.

**Comment by shavyg2** [comment]
ok i will take a little time to set it up.

**Comment by mjackson** [comment]
Please re-open another issue when you have a test case we can look at.
