### ISSUE TITLE
supportsHistory is broken in Brave Browser

### ISSUE THREAD

**Issue by paramsinghvc** [ReactTraining/history#723]
I'm using Brave Browser and hence this userAgent condition is failing

```
function supportsHistory() {
  var ua = window.navigator.userAgent;
  if ((ua.indexOf('Android 2.') !== -1 || ua.indexOf('Android 4.0') !== -1) && ua.indexOf('Mobile Safari') !== -1 && ua.indexOf('Chrome') === -1 && ua.indexOf('Windows Phone') === -1) return false;
  return window.history && 'pushState' in window.history;
}
```

My UA looks like this

`Mozilla/5.0 (Linux; U; Android 4.0; en-us; GT-I9300 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

But it does support latest history apis.

Here's the original issue https://github.com/ReactTraining/react-router/issues/6844

**Comment by mjackson** [comment]
Ah, how thoughtful of Brave to include `Mobile Safari` in its UA string...

I'm honestly not sure the best way to fix this. Open to suggestions.

In the next major version we won't have this problem because we will only support browsers that support the `pushState` API. But it's definitely something to fix in version 4.

**Comment by mjackson** [comment]
Aside: we should probably also add Brave to [our test matrix](https://github.com/ReactTraining/history/blob/master/karma.conf.js#L6-L56) if BrowserStack supports it.

**Comment by damianon** [comment]
why not use feature detection instead of user agent string?

**Comment by mjackson** [comment]
Heads up: we are no longer doing this check in [the v5 beta released this morning](https://github.com/ReactTraining/history/releases/tag/v5.0.0-beta.0). Please give it a shot and LMK how it goes!
