### ISSUE TITLE
How to detect back button navigation vs url refresh?

### ISSUE THREAD

**Issue by MovingGifts** [ReactTraining/history#724]
I have a url at `/page` **(PAGE A)** where I want to detect if the page was navigated to with history back from **(PAGE B)** or if the user was on **(PAGE A)** and manually refreshed the page from the URL bar refresh button (without using history back).

I looked into all the history, location, props by react router but didn't find a way to differentiate how the user navigated to the page.

In both scenarios, the `history.action == 'POP'` is the history action. Ideally it would be `'POP'` when using the back button in the app to go back from page b to page a, and when on page a, when refreshing the page, it would be something other than `'POP'` like `'REFRESH'` for example.

How can we differentiate between both of them to run different logic in our app, since both trigger `'POP'`?

**Comment by mjackson** [comment]
The browser does not give us enough information to tell a back button press from other types of POP events. The best solution I can think of would be to store a counter in `location.state` and then when the location changes see if the new location's count is one less than the previous location.

**Comment by MovingGifts** [comment]
@mjackson Thank you for your comment, I am not fully understanding how this would be accomplished though. Can you share some pseudocode please to show how your proposed solution would work?
