### ISSUE TITLE
Is it still necessary reading hash from href now?

### ISSUE THREAD

**Issue by Tan90Qian** [ReactTraining/history#726]
In the `createHashHistory.js`, there is a comment inner `getHashPath()`
```javascript
 // We can't use window.location.hash here because it's not
 // consistent across browsers - Firefox will pre-decode it!
```
But in the next function `pushHashPath`, it set hash directly.
```javascript
function pushHashPath(path) {
  window.location.hash = path;
}
```
I found the problem of pre-dcode location.hash happened about 6 years ago, and the recent version of firefox is working ok.

**Comment by mjackson** [comment]
It may have changed in recent versions of Firefox, but [we still support Firefox >= 43](https://github.com/ReactTraining/history/blob/master/.browserslistrc#L6). We can remove that code and bump our supported Firefox version, but it will require a major release.

**Comment by StringEpsilon** [comment]
Bumping browsers up in that list should definetly be on the agenda for the next major version.

IE 10 isn't even supported by Microsoft anymore. And the current firefox long term support is version 60.

**Comment by mjackson** [comment]
Heads up: we are no longer doing this in [the v5 beta released earlier today](https://github.com/ReactTraining/history/releases/tag/v5.0.0-beta.0).
