### ISSUE TITLE
What is the location key used for?

### ISSUE THREAD

**Issue by LDWinsky** [ReactTraining/history#733]

**Comment by pshrmn** [comment]
Right now, the only thing that `history` uses a location's `key` for is [reverting a pop navigation](https://github.com/ReactTraining/history/blob/cb4c7a3bfd3010934edfae6e03acb2cdad357498/modules/createBrowserHistory.js#L123-L144).

Some users will use a location's `key` as a unique identifier. This works, but it has caveats that you need to be aware of (e.g. keys are randomly generated, so they won't line up with server rendering).
