### ISSUE TITLE
Re-open - update dependencies due to missing license files

### ISSUE THREAD

**Issue by jeffvandyke** [ReactTraining/history#736]
This was first mentioned in #652, but the packages for `value-equal` and `resolve-pathname` are still old, and still have missing LICENSE files that have been added in newer versions of those packages.

Why did @mjackson close issue #652 without explanation? No update or PR was ever made to `package.json`.

**Comment by mjackson** [comment]
I've re-opened #652. Closing this as a dup. Happy to accept a PR to fix.
