### ISSUE TITLE
history callback doesn't fire

### ISSUE THREAD

**Issue by HosseinAlipour** [ReactTraining/history#739]
I'm using `history.listen` to transform some location properties, e.g., removing a trailing slash. it always gets fired before every component rerenders except browsing back and forward. docs only stated the action is one of PUSH, REPLACE, or POP but never mentioned what happens if it is `goBack` or `goForward`. so, is this really a problem I have? or maybe something is wrong with the library or maybe how React batches updates?

**Comment by pshrmn** [comment]
`goBack` and `goForward` are `POP` navigations. `history` uses a `popstate` listener to catch all `POP` navigations, so it should be working. Please provide an example of where this doesn't work.

**Comment by HosseinAlipour** [comment]
It was probably because the component in which the listening I defined is memoized. I don't have a concrete example but after fixing that, it's now working as expected ever since. I wonder why would ever a memoized component hinder an event-driven function?
