### ISSUE TITLE
getUserConfirmation cannot detect the browser's backward/forward button event

### ISSUE THREAD

**Issue by jiangpingshendd01** [ReactTraining/history#740]
getUserConfirmation cannot detect the navigation of browser's backward/forward button.how  can we detect it with getUserConfirmation

**Comment by pshrmn** [comment]
We are not able to detect pop navigations until the `popstate` event is emitted. This event is emitted _after_ the location changes. `getUserConfirmation` _is_ called with pop navigation; if the user cancels the navigation, then `history` will revert to the previous location. If you are experiencing some behavior that doesn't match up with this, please provide a reproducible example.
