### ISSUE TITLE
Usage with hooks

### ISSUE THREAD

**Issue by damianon** [ReactTraining/history#742]
Maybe I'm missing something obvious here, but how can this be used with the hooks API? Specifically the listen callback

**Comment by TrySound** [comment]
```js
React.useEffect(() => {
  const stopListening = history.listen(() => {})
  return stopListening
}, [history])
```

**Comment by damianon** [comment]
@TrySound I've tried this and in my case this works exactly once. 
inside the listen func i called a function to do the following:
1) get query parameters from url and set state
2) based on state: reload is triggered to fetch items from the server

this works for the first action. after that the callback is still executed, but not even the first step is executed

**Comment by TrySound** [comment]
Could you provide some example?

**Comment by damianon** [comment]
First time loadQuery and search are logged. second time and after only loadQuery is logged

`
    const history = useRef(createBrowserHistory());
    const [Query, setQuery] = useState(defaultQuery);

    useEffect(() => {
        const unlisten = history.current.listen((_l, a) => {
            if (a !== 'POP') return;
            loadUrlParameters();
        });
        return unlisten;
    }, [history]);

    useEffect(() => {
        console.log('search');
        startSearch();
    }, [Query]);

    async function loadUrlParameters() {
        console.log('loadQuery');
        const query = parseQuery(location.search);

        setQuery(query);
    }

    function startSearch() {
        // load items based on Query
    }
`

**Comment by TrySound** [comment]
Where do you define loadUrlParameters and startSearch? Are they in component or module scope? Provide reproducible example in codesandbox please.

**Comment by damianon** [comment]
While writing the codesandbox I found the mistake:
I used { ...defaultState} in loadUrlParameters which only creates a shallow copy and screwed the complete state.
