### ISSUE TITLE
DOMUtils aren't exported properly

### ISSUE THREAD

**Issue by FrankAst** [ReactTraining/history#744]
Early, I've exported `canUseDom` in this way: 
```js
import { canUseDom } from 'history/DOMUtils';
```
Now, it says:

![image](https://user-images.githubusercontent.com/19319629/66068412-5f07fb80-e56f-11e9-8277-774ede301cf9.png)

Then I tried this:
```js
import { canUseDom } from 'history';
```
And got `undefined`:

![image](https://user-images.githubusercontent.com/19319629/66068521-8f4f9a00-e56f-11e9-8b3a-5fcdcaf8c8a9.png)

Eventually, I looked for sources and realize that `canUseDom` isn't exported at all.
The `DOMUtils.js` in the root directory tries to import utils from `index.js`, then from `cjs`. And there is no such export. The same situation with `es` & `esm` folder.

So, my question is how can I import `canUseDom`?
I think in `history.js` file should be something like this: 
```js
exports.createBrowserHistory = createBrowserHistory;
exports.createHashHistory = createHashHistory;
exports.createMemoryHistory = createMemoryHistory;
exports.createLocation = createLocation;
exports.locationsAreEqual = locationsAreEqual;
exports.parsePath = parsePath;
exports.createPath = createPath;
exports.canUseDom = canUseDom; // added this line
```

**Comment by pshrmn** [comment]
The DOM utils are not, and have never been, public API. You could access them previously because the published package had multiple modules, but access goes away completely when we switch to a single module.

The deprecation warning is just unclear because it is a generic message that was more appropriate for the actually public API exports.

**Comment by FrankAst** [comment]
Thanks for replying! In that case, there is no way to use `canUseDom` anymore?

**Comment by pshrmn** [comment]
I would just copy the code:

```js
const canUseDOM = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
);
```

**Comment by FrankAst** [comment]
Ok, will do that. Thanks!
