### ISSUE TITLE
createBrowserHistory is undefined in history import

### ISSUE THREAD

**Issue by TKB21** [ReactTraining/history#752]
I'm currently using v5 of React Router DOM. My goal is to create a history object so that I can manipulate my page locations in my redux actions. In past projects I imported the `createBrowserHistory` function as so:

    import createBrowserHistory from 'history/createBrowserHistory'
    
    export default createBrowserHistory();

With this setup though I get the deprecation warning:

    Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.

I changed my import to just:

    import createBrowserHistory from 'history';

But at this point `createBrowserHistory` comes up as `undefined`. I'm at a loss at this point. Any help would be greatly appreciated. Below is what my `yarn.lock` file looks like:

    react-router-dom@^5.1.2:
      version "5.1.2"
      resolved "https://registry.yarnpkg.com/react-router-dom/-/react-router-dom-5.1.2.tgz#06701b834352f44d37fbb6311f870f84c76b9c18"
      integrity sha512-7BPHAaIwWpZS074UKaw1FjVdZBSVWEk8IuDXdB+OkLb8vd/WRQIpA4ag9WQk61aEfQs47wHyjWUoUGGZxpQXew==
      dependencies:
        "@babel/runtime" "^7.1.2"
        history "^4.9.0"
        loose-envify "^1.3.1"
        prop-types "^15.6.2"
        react-router "5.1.2"
        tiny-invariant "^1.0.2"
        tiny-warning "^1.0.0"

**Comment by miraage** [comment]
[Docs](https://github.com/ReactTraining/history/blob/master/docs/GettingStarted.md).

`import { createBrowserHistory } from 'history';`

**Comment by TKB21** [comment]
> [Docs](https://github.com/ReactTraining/history/blob/master/docs/GettingStarted.md).
> 
> `import { createBrowserHistory } from 'history';`

Unfortunately I get the same error message.

**Comment by TKB21** [comment]
I should also note that after console logging the history object itself it shows up as an empty object.

**Comment by miraage** [comment]
@TKB21 https://codesandbox.io/embed/musing-satoshi-r9f6x

**Comment by cbanksbi** [comment]
I finally managed to get this to work. I had a yarn.lock and package.lock file both in my project and needed to remove package.lock per the warning I was getting in my console. I don't know if this was exactly the issue but after doing this and upgrading my packages as a whole I managed to get it to work. Thanks for your responsiveness.

**Comment by TKB21** [comment]
@miraage I finally managed to get this to work. I had a yarn.lock and package.lock file both in my project and needed to remove package.lock per the warning I was getting in my console. I don't know if this was exactly the issue but after doing this and upgrading my packages as a whole I managed to get it to work. Thanks for your responsiveness.
