### ISSUE TITLE
How to Pop and then Replace State?

### ISSUE THREAD

**Issue by ryanrossiter** [ReactTraining/history#765]
In my application I need to perform 2 navigation operations one after another to acheive the desired history state:
1. POP/goBack
2. Replace the page

Is this possible? When I try to do this it will go back and then throw an error that I'm trying to update an unmounted component.

**Comment by richardgorman** [comment]
This sounds like an architectural issue with your application. If you're trying to update a non-existent component then of course you will have an undesired effect.

However, this is not the package where you should report on such things. This package is an API wrapper between developers and their environment.

**Comment by ryanrossiter** [comment]
Hi Richard, you're right that the error about updating an unmounted component was a red herring - that was a separate issue in my application.

But I'm still having trouble causing 2 navigations in quick succession, here is my navigation code:
```javascript
history.goBack();
console.log(history.location);
history.replace('/');
console.log(history.location);
```
And this will print:
```
{pathname: "...the last path...", search: "", hash: "", state: undefined, key: "6s5eeo"}
{pathname: "/", search: "", hash: "", state: undefined, key: "3c1bk4"}
```
Which seems correct, but the browser only navigates to the last path (as triggered by `goBack`) so that leads me to believe that the 2nd navigation isn't being handled by the browser. Is this something you would expect to work? I am using BrowserRouter.

**Comment by pshrmn** [comment]
`history.goBack` calls `window.history.go(-1)`, which is asynchronous. I believe that what is happening is that the `replace` is happening before the pop. After you run your `goBack` and `replace`, does clicking the browser's forward button take you to the replace location? If so, you need to also make the replace asynchronous (e.g. put it in a `setTimeout`).

**Comment by ryanrossiter** [comment]
@pshrmn you're right that's exactly what was happening! Wrapping the 2nd navigation call in a `setTimeout` produces the behaviour I was expecting. Thanks so much.

For others that may encounter this later here's what I ended with:
```javascript
history.goBack();
setTimeout(() => {
  history.replace('/');
});
```

**Comment by jailsonpaca** [comment]
> Hi Richard, you're right that the error about updating an unmounted component was a red herring - that was a separate issue in my application, sorry for the confusion.
> 
> But I'm still having trouble causing 2 navigations in quick succession, here is my navigation code:
> 
> ```js
> history.goBack();
> console.log(history.location);
> history.replace('/');
> console.log(history.location);
> ```
> 
> And this will print:
> 
> ```
> {pathname: "...the last path...", search: "", hash: "", state: undefined, key: "6s5eeo"}
> {pathname: "/", search: "", hash: "", state: undefined, key: "3c1bk4"}
> ```
> 
> Which seems correct, but the browser only navigates to the last path (as triggered by `goBack`) so that leads me to believe that the 2nd navigation isn't being handled by the browser. Is this something you would expect to work? I am using BrowserRouter.

thanks! God Bless you
