### ISSUE TITLE
Feature: Missing a way to listen to history changes before they change the browser URL

### ISSUE THREAD

**Issue by douglas-treadwell** [ReactTraining/history#789]
This issue is in the context of a React application using React Router, but the feature needed would most appropriately belong to this library (history), in my opinion.

I'm familiar with `history.block` and how it permits preventing URL transitions entirely.

I'm also familiar with the previous discussion about `history.listenBefore` at https://github.com/ReactTraining/history/issues/379.
Relevant quote below.

> The use case for history.listenBefore was to block changes to the URL. Essentially, you would return false or a prompt message from your listenBefore hook which would let you block the transition.

> The API in v4 for this is `history.block()`.

However, what if my use case is not to block all changes to the URL, but instead to block or redirect only some of them?  I want to intercept the intended URL change, check some conditions, and either let the URL change happen or redirect it somewhere else.  Something similar to the old Angular UI-Router's "onStateChangeStart".

Again, in my use case, I don't want to block all URL changes, only some.  I also don't want to prompt the user with a dialog.  For example, using react-router BrowserRouter's getUserConfirmation.

I could create a component similar to [PrivateRoute](https://reacttraining.com/react-router/web/example/auth-workflow) as shown in the React Router docs.  However, the user would still briefly be taken to the route we want to prevent them from accessing.  I'd like to intercept the change and prevent it.

I could also check for the URL change within my top-level component.  But that would only permit me to detect changes after the browser URL had changed.  I want to detect the intended change before that.

Another option would be to use the `getUserConfirmation` parameter to BrowserRouter, passing a function that performs some logic rather than prompting the user for a response.  Given the name of the parameter, that just doesn't seem what it was intended to be used for, so perhaps using it in an unplanned way will not work the way I expect or might be broken in future versions.

Finally, the option I lean toward is wrapping `history` with a "history proxy", where I wrap `history.push`, `history.pop`, and possibly other methods, to check some conditions before calling the original implementations.  Using something like PrivateRoute would still be necessary to handle users clicking the back button, and probably the initial page load.

**However, this library (history) previously supported this sort of requirement through `history.listenBefore`.  Could that method be brought back?  Or is there some other mechanism for accomplishing what I'm trying to do that I'm not aware of?**

Also note that this capability may enable someone to build their own solution to issues such as https://github.com/ReactTraining/history/issues/651 on top of it, or create compatible libraries.

Also, if anyone has any comments or suggestions about my proposed solutions (and especially the `history proxy` solution), I'd appreciate any input.

**Comment by douglas-treadwell** [comment]
@mjackson I took a look at the `dev` branch and I see the [future version of `history.block`](https://github.com/ReactTraining/history/blob/dev/docs/blocking-transitions.md), which is passed a transition object, likely handles this use case.

It seems like the new `history.block` is a sort of combination of the old `history.block` and `history.listenBefore`.  I see that a beta version is available.  I'll try that.

What do you think about the naming of `history.block` now that it handles more than just blocking?  Would it be more discoverable if it were aliased to `history.beforeTransition` or something similar?

**Comment by douglas-treadwell** [comment]
Closing my own issue.  Existing and upcoming features are sufficient to handle my use case.

**Comment by grundmanise** [comment]
We have a similar use-case for the `history.block`, it's used as a `redirect` handler in our case. And we also don't use it's dialog functionality. Perhaps our use-cases are not that niche, just not so many people comment here.

```
history.block((location) => {
    const redirectLocation = getRedirectLocation(location);
    if (redirectLocation) {
        history.replace(redirectLocation);
    }
    return !redirectLocation
});

```

**Comment by cherlo** [comment]
As of today the current version (5.3.2) of history.block triggers AFTER the URL is pushed when using the browser back button.  I came up with a complicated way of repairing the history after history.block, but it would be must more preferable if history.block actually blocked the push.  All it appears to have done is block the rendering of the new route.

**Comment by khedau1** [comment]
How to fix @cherlo mentioned problem related to browser back button?
