### ISSUE TITLE
[feature request] Add `toString` method to location

### ISSUE THREAD

**Issue by afzalsayed96** [ReactTraining/history#799]
Ref ReactTraining/react-router#7405

It might be useful to have a `toString` method for location object which can be used to get a fully constructed pathname - `/pathname#hash?search` .

Example usage
```jsx
import { Navigate, useLocation } from 'react-router-dom'

function LoginRedirect() {
  const location = useLocation()

  return <Navigate to={`/login?redirect=${location.toString()}`} >
}
```

**Comment by afzalsayed96** [comment]
I would be happy to contribute to implement this feature

**Comment by mjackson** [comment]
We already have a `createPath` method:

```js
import { createPath } from 'history';
let string = createPath(location);
```
