### ISSUE TITLE
Incorrect types for push

### ISSUE THREAD

**Issue by TeoTN** [ReactTraining/history#802]
It seems that `history.push` is typed incorrectly. I'm trying to pass the function as reference to redux-saga's `call` effect which causes an error:

```
const path: History.Path = ...;
yield call({ context: history, fn: history.push }, path);
```

The error is:
```
TS2769: No overload matches this call. Argument of type 'string' is not assignable to parameter of type 'LocationDescriptorObject<PoorMansUnknown>'.
```

**Comment by mjackson** [comment]
It looks like you're using the types for version 4 which are maintained in https://github.com/DefinitelyTyped/DefinitelyTyped. You'll probably want to open an issue over there instead of here.
