### ISSUE TITLE
Expose previous location when using history.listen

### ISSUE THREAD

**Issue by andrewplummer** [ReactTraining/history#817]
I can't really understand why the previous location isn't exposed when using `history.listen`.
This seems like critical information, especially given that route changes occur even on hash updates, which often need to be differentiated from actual route updates to determine whether or not to show a new screen.

**Comment by mjackson** [comment]
```js
let prevLocation = history.location;
history.listen(location => {
  // Do whatever you want with the previous location here.
  prevLocation = location;
});
```

**Comment by andrewplummer** [comment]
```
  componentDidMount() {
    this.lastProps = this.props;
  }
  componentDidUpdate() {
    // Do whatever you want with the previous props

    // Then update lastProps for the next time around
    this.lastProps = this.props;
  }
```

Just roll your own state machine! ... says the library providing the state

**Comment by mjackson** [comment]
I've always thought of history.listen as more of an event emitter than a state machine. There are so many other tools for managing state (this.state/this.setState, useState, useReducer, etc).

I really don't want to throw another one on the pile 😅

**Comment by andrewplummer** [comment]
A change in URL represents a change in the history's state, no? This seems to be the domain of the library providing access to the history (and its associated state). Of course you could make a case that the history API itself should be exposing this, which it doesn't and it's rather deficient here (also because it doesn't expose `push` events) ... but that's all the more reason that something like this is so sorely needed.

Requiring users to duplicate this in their application state just creates more potential points of failure, especially if you were to have to duplicate this across multiple components/consumers that would all have to now concern themselves with staying synced.
