### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by tnguyen14** [ReactTraining/history#821]
I am using `history` as suggested in my Svelte app (with rollup compilation):

```js
import history from 'history/browser';

history.replace('/');
```

However, I am getting the following error in the browser:

```
Uncaught ReferenceError: process is not defined
```

I can see in the node_modules package `browser.js` file has references to `process.env`. Is this expected? Should a browser bundle include such node globals?

**Comment by TrySound** [comment]
This is convention used in many javascript (including browser) libraries. You should add "replace" plugin to your rollup build.
```js
replace({
  'process.env.NODE_ENV': JSON.stringify('production') // or JSON.stringify('development')
})
```

**Comment by tnguyen14** [comment]
Thanks. I have the replace plugin, just didn't think it should be a requirement for this library.

Will do that to avoid this error now.

**Comment by tnguyen14** [comment]
Perhaps this could be documented more prominently?

**Comment by cpiber** [comment]
I agree, this should be documented.
