### ISSUE TITLE
History.push() and replace() not working in React while using history@5.0.0

### ISSUE THREAD

**Issue by AnkitKumar1311** [ReactTraining/history#834]

**Comment by StringEpsilon** [comment]
Duplicate of #803 / #805 / #811

**Comment by AnkitKumar1311** [comment]
> Duplicate of #803 / #805 / #811
> 
> The break is pretty much intentional, just not documented in the release notes.

Is there any way I can work around it without going back to the previous stable version ?

**Comment by StringEpsilon** [comment]
What breaks is actually the way the listeners are called. Unless you can adapt whatever is listening to the new calling conventions, you either have to make some wrapper (by overriding `.listen()`, maybe?) or downgrade.

I tried to collect what I could about the technical changes in this gist: https://gist.github.com/StringEpsilon/47820cc961c8d82f3b71dc856b5cc616 Hope that helps.
