### ISSUE TITLE
Type signature for History.listen specifies the wrong return type

### ISSUE THREAD

**Issue by adamkovalsky** [ReactTraining/history#849]
The type signature for `History.listen` specifies the return type as `void`, while the function actually returns a cleanup function.

**Comment by StringEpsilon** [comment]
The type definitions for version 5.0 specify 

```ts
  listen(listener: Listener<S>): () => void;
```
Which is correct. `() => void` is just another way to say `function`.

Out of curiosity, I checked the type definitions for 4.10.x (in the @types/history package), which specifies:

```ts
export type UnregisterCallback = () => void;
//...
listen(listener: LocationListener<HistoryLocationState>): UnregisterCallback;
```

**Comment by adamkovalsky** [comment]
You are, of course, correct. I'm not sure what I was seeing when I opened this, but I guess I was wrong.

**Comment by StringEpsilon** [comment]
I misread `() => void` too sometimes :)
