### ISSUE TITLE
The way blockers are called in v.5's replace/push broke our app

### ISSUE THREAD

**Issue by BingWangEd** [ReactTraining/history#867]
We upgraded to History 5 and we found `history.replace` was not able to update the `history`. I dug into the source code and this is what I found.

In v.5, when `history.replace` is called [here](https://github.com/ReactTraining/history/blob/28c89f4091ae9e1b0001341ea60c629674e83627/packages/history/index.ts#L976), it would check [allowTx](https://github.com/ReactTraining/history/blob/28c89f4091ae9e1b0001341ea60c629674e83627/packages/history/index.ts#L931). If my understanding is correct, `allowTx` would always return false if there’s any functions push to `blockers`.

This is a behavioral change from v.4, in which the `replace` function [here](https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/createMemoryHistory.js#L105) would still update `history.enries`, if the result from `blocker` function [here](https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/createTransitionManager.js#L42) is not false.

Please correct me if I got anything wrong, but when I commented out any callback we push to `blockers` via `history.block`, the app indeed loads as expected. Is this an intentional change? I don't think I found it in [documentation](https://gist.github.com/StringEpsilon/47820cc961c8d82f3b71dc856b5cc616) or in the [undocumented one](https://github.com/ReactTraining/history/issues/811).

**Comment by StringEpsilon** [comment]
Hi, the gist and github issue you linked are not the official documentation. Just something I compiled.

The change in blocking behavior is alluded to in the 5.0 beta release notes [here](https://github.com/ReactTraining/history/releases/tag/v5.0.0-beta.0)  and the version 5 [documentation here](https://github.com/ReactTraining/history/blob/master/docs/blocking-transitions.md). I've linked that latter one in my gist under the "Blocking transitions" headline, stating that 

> The entire blocking system has been redesigned from scratch and is therefore completely incompatible.

**Comment by BingWangEd** [comment]
I see. Thanks for the quick response! Closing this issue now
