### ISSUE TITLE
Using multiple instances of createBrowserHistory

### ISSUE THREAD

**Issue by plazek** [ReactTraining/history#868]
Everywhere I've seen, the recommendation is to use a single instance of `history` that is then passed around and used as needed, e.g.
```
// history.js
import { createBrowserHistory } from 'history';

const history = createBrowserHistory();
export default history;
```

But I'm interested in using multiple instances of `history` for a [micro-frontend](https://martinfowler.com/articles/micro-frontends.html) implementation. One of the paradigms of MFEs is that you should avoid sharing state whenever possible, and passing around a single `history` instance is unwieldy and a slight anti-pattern.

After pouring over the code, it appears that when you instantiate an instance of `history` [it simply uses the global history singleton](https://github.com/ReactTraining/history/blob/28c89f4091ae9e1b0001341ea60c629674e83627/packages/history/index.ts#L401). 

So my question is this: is it acceptable to use multiple instances of `createBrowserHistory`, given that this simply establishes an interface the browser API that always uses the same instance of history behind the scenes? Or is there truly a reason that only a single instance of `history` should be used across your application?

**Comment by pshrmn** [comment]
If you have two browser histories, A and B and navigate using A, B will not know about the navigation and will think that the app is still at the previous location.

**Comment by plazek** [comment]
Thanks for the quick response @pshrmn - that makes sense 👍
